const { Sequelize, DataTypes } = require("sequelize");
const db = require("../config/Dbconnect.js");

const coating_1_daily = db.define(
  "coating_1_daily",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Unw_Vis: DataTypes.BOOLEAN,
    Unw_Stet: DataTypes.BOOLEAN,
    Unw_ArusR: DataTypes.DECIMAL(5, 2),
    Unw_ArusS: DataTypes.DECIMAL(5, 2),
    Unw_ArusT: DataTypes.DECIMAL(5, 2),
    Unw_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Unw_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Unw_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Unw_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Unw_TempM: DataTypes.DECIMAL(5, 2),
    Unw_Ket: DataTypes.TEXT,
    MainDrv_Vis: DataTypes.BOOLEAN,
    MainDrv_Stet: DataTypes.BOOLEAN,
    MainDrv_ArusR: DataTypes.DECIMAL(5, 2),
    MainDrv_ArusS: DataTypes.DECIMAL(5, 2),
    MainDrv_ArusT: DataTypes.DECIMAL(5, 2),
    MainDrv_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MainDrv_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MainDrv_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MainDrv_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MainDrv_TempM: DataTypes.DECIMAL(5, 2),
    MainDrv_Ket: DataTypes.TEXT,
    GrvRolPrm_Vis: DataTypes.BOOLEAN,
    GrvRolPrm_Stet: DataTypes.BOOLEAN,
    GrvRolPrm_ArusR: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_ArusS: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_ArusT: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VDE_Vms: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VDE_Vge: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_TempM: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_Ket: DataTypes.TEXT,
    ColRol1_Vis: DataTypes.BOOLEAN,
    ColRol1_Stet: DataTypes.BOOLEAN,
    ColRol1_ArusR: DataTypes.DECIMAL(5, 2),
    ColRol1_ArusS: DataTypes.DECIMAL(5, 2),
    ColRol1_ArusT: DataTypes.DECIMAL(5, 2),
    ColRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ColRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ColRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ColRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ColRol1_TempM: DataTypes.DECIMAL(5, 2),
    ColRol1_Ket: DataTypes.TEXT,
    SucRol_Vis: DataTypes.BOOLEAN,
    SucRol_Stet: DataTypes.BOOLEAN,
    SucRol_ArusR: DataTypes.DECIMAL(5, 2),
    SucRol_ArusS: DataTypes.DECIMAL(5, 2),
    SucRol_ArusT: DataTypes.DECIMAL(5, 2),
    SucRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    SucRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    SucRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    SucRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    SucRol_TempM: DataTypes.DECIMAL(5, 2),
    SucRol_Ket: DataTypes.TEXT,
    ColRol2_Vis: DataTypes.BOOLEAN,
    ColRol2_Stet: DataTypes.BOOLEAN,
    ColRol2_ArusR: DataTypes.DECIMAL(5, 2),
    ColRol2_ArusS: DataTypes.DECIMAL(5, 2),
    ColRol2_ArusT: DataTypes.DECIMAL(5, 2),
    ColRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ColRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ColRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ColRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ColRol2_TempM: DataTypes.DECIMAL(5, 2),
    ColRol2_Ket: DataTypes.TEXT,
    RwdA_Vis: DataTypes.BOOLEAN,
    RwdA_Stet: DataTypes.BOOLEAN,
    RwdA_ArusR: DataTypes.DECIMAL(5, 2),
    RwdA_ArusS: DataTypes.DECIMAL(5, 2),
    RwdA_ArusT: DataTypes.DECIMAL(5, 2),
    RwdA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdA_TempM: DataTypes.DECIMAL(5, 2),
    RwdA_Ket: DataTypes.TEXT,
    RwdB_Vis: DataTypes.BOOLEAN,
    RwdB_Stet: DataTypes.BOOLEAN,
    RwdB_ArusR: DataTypes.DECIMAL(5, 2),
    RwdB_ArusS: DataTypes.DECIMAL(5, 2),
    RwdB_ArusT: DataTypes.DECIMAL(5, 2),
    RwdB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdB_TempM: DataTypes.DECIMAL(5, 2),
    RwdB_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_1_weekly = db.define(
  "coating_1_weekly",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    FanTrtUnw_Vis: DataTypes.BOOLEAN,
    FanTrtUnw_Stet: DataTypes.BOOLEAN,
    FanTrtUnw_ArusR: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_ArusS: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_ArusT: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_TempM: DataTypes.DECIMAL(5, 2),
    FanTrtUnw_Ket: DataTypes.TEXT,
    FanUnw_Vis: DataTypes.BOOLEAN,
    FanUnw_Stet: DataTypes.BOOLEAN,
    FanUnw_ArusR: DataTypes.DECIMAL(5, 2),
    FanUnw_ArusS: DataTypes.DECIMAL(5, 2),
    FanUnw_ArusT: DataTypes.DECIMAL(5, 2),
    FanUnw_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanUnw_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanUnw_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanUnw_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanUnw_TempM: DataTypes.DECIMAL(5, 2),
    FanUnw_Ket: DataTypes.TEXT,
    FanMainDrv_Vis: DataTypes.BOOLEAN,
    FanMainDrv_Stet: DataTypes.BOOLEAN,
    FanMainDrv_ArusR: DataTypes.DECIMAL(5, 2),
    FanMainDrv_ArusS: DataTypes.DECIMAL(5, 2),
    FanMainDrv_ArusT: DataTypes.DECIMAL(5, 2),
    FanMainDrv_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMainDrv_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMainDrv_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMainDrv_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMainDrv_TempM: DataTypes.DECIMAL(5, 2),
    FanMainDrv_Ket: DataTypes.TEXT,
    BlwCor_Vis: DataTypes.BOOLEAN,
    BlwCor_Stet: DataTypes.BOOLEAN,
    BlwCor_ArusR: DataTypes.DECIMAL(5, 2),
    BlwCor_ArusS: DataTypes.DECIMAL(5, 2),
    BlwCor_ArusT: DataTypes.DECIMAL(5, 2),
    BlwCor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    BlwCor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    BlwCor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    BlwCor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    BlwCor_TempM: DataTypes.DECIMAL(5, 2),
    BlwCor_Ket: DataTypes.TEXT,
    ExhCor_Vis: DataTypes.BOOLEAN,
    ExhCor_Stet: DataTypes.BOOLEAN,
    ExhCor_ArusR: DataTypes.DECIMAL(5, 2),
    ExhCor_ArusS: DataTypes.DECIMAL(5, 2),
    ExhCor_ArusT: DataTypes.DECIMAL(5, 2),
    ExhCor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhCor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhCor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhCor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhCor_TempM: DataTypes.DECIMAL(5, 2),
    ExhCor_Ket: DataTypes.TEXT,
    FanGrvRolPrm_Vis: DataTypes.BOOLEAN,
    FanGrvRolPrm_Stet: DataTypes.BOOLEAN,
    FanGrvRolPrm_ArusR: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_ArusS: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_ArusT: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_TempM: DataTypes.DECIMAL(5, 2),
    FanGrvRolPrm_Ket: DataTypes.TEXT,
    PmpCoatRolLtx_Vis: DataTypes.BOOLEAN,
    PmpCoatRolLtx_Stet: DataTypes.BOOLEAN,
    PmpCoatRolLtx_ArusR: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_ArusS: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_ArusT: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_TempM: DataTypes.DECIMAL(5, 2),
    PmpCoatRolLtx_Ket: DataTypes.TEXT,
    Dry1Sct1_1_Vis: DataTypes.BOOLEAN,
    Dry1Sct1_1_Stet: DataTypes.BOOLEAN,
    Dry1Sct1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_TempM: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_1_Ket: DataTypes.TEXT,
    Dry1Sct1_2_Vis: DataTypes.BOOLEAN,
    Dry1Sct1_2_Stet: DataTypes.BOOLEAN,
    Dry1Sct1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_TempM: DataTypes.DECIMAL(5, 2),
    Dry1Sct1_2_Ket: DataTypes.TEXT,
    Dry1Sct2_1_Vis: DataTypes.BOOLEAN,
    Dry1Sct2_1_Stet: DataTypes.BOOLEAN,
    Dry1Sct2_1_ArusR: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_ArusS: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_ArusT: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_TempM: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_1_Ket: DataTypes.TEXT,
    Dry1Sct2_2_Vis: DataTypes.BOOLEAN,
    Dry1Sct2_2_Stet: DataTypes.BOOLEAN,
    Dry1Sct2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_TempM: DataTypes.DECIMAL(5, 2),
    Dry1Sct2_2_Ket: DataTypes.TEXT,
    FanColRol1_Vis: DataTypes.BOOLEAN,
    FanColRol1_Stet: DataTypes.BOOLEAN,
    FanColRol1_ArusR: DataTypes.DECIMAL(5, 2),
    FanColRol1_ArusS: DataTypes.DECIMAL(5, 2),
    FanColRol1_ArusT: DataTypes.DECIMAL(5, 2),
    FanColRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanColRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanColRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanColRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanColRol1_TempM: DataTypes.DECIMAL(5, 2),
    FanColRol1_Ket: DataTypes.TEXT,
    FanGrvRolLtx_Vis: DataTypes.BOOLEAN,
    FanGrvRolLtx_Stet: DataTypes.BOOLEAN,
    FanGrvRolLtx_ArusR: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_ArusS: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_ArusT: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_TempM: DataTypes.DECIMAL(5, 2),
    FanGrvRolLtx_Ket: DataTypes.TEXT,
    PmpCoatLtx_Vis: DataTypes.BOOLEAN,
    PmpCoatLtx_Stet: DataTypes.BOOLEAN,
    PmpCoatLtx_ArusR: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_ArusS: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_ArusT: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_TempM: DataTypes.DECIMAL(5, 2),
    PmpCoatLtx_Ket: DataTypes.TEXT,
    MixSilCoatLtx_Vis: DataTypes.BOOLEAN,
    MixSilCoatLtx_Stet: DataTypes.BOOLEAN,
    MixSilCoatLtx_ArusR: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_ArusS: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_ArusT: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_TempM: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_Ket: DataTypes.TEXT,
    ExhIR_Vis: DataTypes.BOOLEAN,
    ExhIR_Stet: DataTypes.BOOLEAN,
    ExhIR_ArusR: DataTypes.DECIMAL(5, 2),
    ExhIR_ArusS: DataTypes.DECIMAL(5, 2),
    ExhIR_ArusT: DataTypes.DECIMAL(5, 2),
    ExhIR_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhIR_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhIR_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhIR_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhIR_TempM: DataTypes.DECIMAL(5, 2),
    ExhIR_Ket: DataTypes.TEXT,
    ExhSucRol_Vis: DataTypes.BOOLEAN,
    ExhSucRol_Stet: DataTypes.BOOLEAN,
    ExhSucRol_ArusR: DataTypes.DECIMAL(5, 2),
    ExhSucRol_ArusS: DataTypes.DECIMAL(5, 2),
    ExhSucRol_ArusT: DataTypes.DECIMAL(5, 2),
    ExhSucRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhSucRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhSucRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhSucRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhSucRol_TempM: DataTypes.DECIMAL(5, 2),
    ExhSucRol_Ket: DataTypes.TEXT,
    Dry2Sct1_Vis: DataTypes.BOOLEAN,
    Dry2Sct1_Stet: DataTypes.BOOLEAN,
    Dry2Sct1_ArusR: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_ArusS: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_ArusT: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_TempM: DataTypes.DECIMAL(5, 2),
    Dry2Sct1_Ket: DataTypes.TEXT,
    Dry2Sct2_Vis: DataTypes.BOOLEAN,
    Dry2Sct2_Stet: DataTypes.BOOLEAN,
    Dry2Sct2_ArusR: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_ArusS: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_ArusT: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_TempM: DataTypes.DECIMAL(5, 2),
    Dry2Sct2_Ket: DataTypes.TEXT,
    Dry2Sct3_Vis: DataTypes.BOOLEAN,
    Dry2Sct3_Stet: DataTypes.BOOLEAN,
    Dry2Sct3_ArusR: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_ArusS: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_ArusT: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_TempM: DataTypes.DECIMAL(5, 2),
    Dry2Sct3_Ket: DataTypes.TEXT,
    Dry2Sct4_Vis: DataTypes.BOOLEAN,
    Dry2Sct4_Stet: DataTypes.BOOLEAN,
    Dry2Sct4_ArusR: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_ArusS: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_ArusT: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_TempM: DataTypes.DECIMAL(5, 2),
    Dry2Sct4_Ket: DataTypes.TEXT,
    Dry2Sct5_Vis: DataTypes.BOOLEAN,
    Dry2Sct5_Stet: DataTypes.BOOLEAN,
    Dry2Sct5_ArusR: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_ArusS: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_ArusT: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_TempM: DataTypes.DECIMAL(5, 2),
    Dry2Sct5_Ket: DataTypes.TEXT,
    DryExhIn_Vis: DataTypes.BOOLEAN,
    DryExhIn_Stet: DataTypes.BOOLEAN,
    DryExhIn_ArusR: DataTypes.DECIMAL(5, 2),
    DryExhIn_ArusS: DataTypes.DECIMAL(5, 2),
    DryExhIn_ArusT: DataTypes.DECIMAL(5, 2),
    DryExhIn_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryExhIn_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryExhIn_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryExhIn_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryExhIn_TempM: DataTypes.DECIMAL(5, 2),
    DryExhIn_Ket: DataTypes.TEXT,
    DryExhOut_Vis: DataTypes.BOOLEAN,
    DryExhOut_Stet: DataTypes.BOOLEAN,
    DryExhOut_ArusR: DataTypes.DECIMAL(5, 2),
    DryExhOut_ArusS: DataTypes.DECIMAL(5, 2),
    DryExhOut_ArusT: DataTypes.DECIMAL(5, 2),
    DryExhOut_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryExhOut_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryExhOut_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryExhOut_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryExhOut_TempM: DataTypes.DECIMAL(5, 2),
    DryExhOut_Ket: DataTypes.TEXT,
    FanColRol2_Vis: DataTypes.BOOLEAN,
    FanColRol2_Stet: DataTypes.BOOLEAN,
    FanColRol2_ArusR: DataTypes.DECIMAL(5, 2),
    FanColRol2_ArusS: DataTypes.DECIMAL(5, 2),
    FanColRol2_ArusT: DataTypes.DECIMAL(5, 2),
    FanColRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanColRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanColRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanColRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanColRol2_TempM: DataTypes.DECIMAL(5, 2),
    FanColRol2_Ket: DataTypes.TEXT,
    FanRwdA_Vis: DataTypes.BOOLEAN,
    FanRwdA_Stet: DataTypes.BOOLEAN,
    FanRwdA_ArusR: DataTypes.DECIMAL(5, 2),
    FanRwdA_ArusS: DataTypes.DECIMAL(5, 2),
    FanRwdA_ArusT: DataTypes.DECIMAL(5, 2),
    FanRwdA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanRwdA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanRwdA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanRwdA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanRwdA_TempM: DataTypes.DECIMAL(5, 2),
    FanRwdA_Ket: DataTypes.TEXT,
    FanRwdB_Vis: DataTypes.BOOLEAN,
    FanRwdB_Stet: DataTypes.BOOLEAN,
    FanRwdB_ArusR: DataTypes.DECIMAL(5, 2),
    FanRwdB_ArusS: DataTypes.DECIMAL(5, 2),
    FanRwdB_ArusT: DataTypes.DECIMAL(5, 2),
    FanRwdB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanRwdB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanRwdB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanRwdB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanRwdB_TempM: DataTypes.DECIMAL(5, 2),
    FanRwdB_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_1_monthly = db.define(
  "coating_1_monthly",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    UwdTur_Vis: DataTypes.BOOLEAN,
    UwdTur_Stet: DataTypes.BOOLEAN,
    UwdTur_ArusR: DataTypes.DECIMAL(5, 2),
    UwdTur_ArusS: DataTypes.DECIMAL(5, 2),
    UwdTur_ArusT: DataTypes.DECIMAL(5, 2),
    UwdTur_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UwdTur_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UwdTur_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UwdTur_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UwdTur_TempM: DataTypes.DECIMAL(5, 2),
    UwdTur_Ket: DataTypes.TEXT,
    RwdTur_Vis: DataTypes.BOOLEAN,
    RwdTur_Stet: DataTypes.BOOLEAN,
    RwdTur_ArusR: DataTypes.DECIMAL(5, 2),
    RwdTur_ArusS: DataTypes.DECIMAL(5, 2),
    RwdTur_ArusT: DataTypes.DECIMAL(5, 2),
    RwdTur_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdTur_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdTur_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdTur_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdTur_TempM: DataTypes.DECIMAL(5, 2),
    RwdTur_Ket: DataTypes.TEXT,
    PmpOilDry1_1_Vis: DataTypes.BOOLEAN,
    PmpOilDry1_1_Stet: DataTypes.BOOLEAN,
    PmpOilDry1_1_ArusR: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_ArusS: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_ArusT: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_TempM: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_1_Ket: DataTypes.TEXT,
    PmpOilDry1_2_Vis: DataTypes.BOOLEAN,
    PmpOilDry1_2_Stet: DataTypes.BOOLEAN,
    PmpOilDry1_2_ArusR: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_ArusS: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_ArusT: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_TempM: DataTypes.DECIMAL(5, 2),
    PmpOilDry1_2_Ket: DataTypes.TEXT,
    PmpOilDry2_1_Vis: DataTypes.BOOLEAN,
    PmpOilDry2_1_Stet: DataTypes.BOOLEAN,
    PmpOilDry2_1_ArusR: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_ArusS: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_ArusT: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_TempM: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_1_Ket: DataTypes.TEXT,
    PmpOilDry2_2_Vis: DataTypes.BOOLEAN,
    PmpOilDry2_2_Stet: DataTypes.BOOLEAN,
    PmpOilDry2_2_ArusR: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_ArusS: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_ArusT: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_TempM: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_2_Ket: DataTypes.TEXT,
    PmpOilDry2_3_Vis: DataTypes.BOOLEAN,
    PmpOilDry2_3_Stet: DataTypes.BOOLEAN,
    PmpOilDry2_3_ArusR: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_ArusS: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_ArusT: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_TempM: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_3_Ket: DataTypes.TEXT,
    PmpOilDry2_5_Vis: DataTypes.BOOLEAN,
    PmpOilDry2_5_Stet: DataTypes.BOOLEAN,
    PmpOilDry2_5_ArusR: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_ArusS: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_ArusT: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_TempM: DataTypes.DECIMAL(5, 2),
    PmpOilDry2_5_Ket: DataTypes.TEXT,
    ElecCor_Vis: DataTypes.BOOLEAN,
    ElecCor_Stet: DataTypes.BOOLEAN,
    ElecCor_ArusR: DataTypes.DECIMAL(5, 2),
    ElecCor_ArusS: DataTypes.DECIMAL(5, 2),
    ElecCor_ArusT: DataTypes.DECIMAL(5, 2),
    ElecCor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ElecCor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ElecCor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ElecCor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ElecCor_TempM: DataTypes.DECIMAL(5, 2),
    ElecCor_Ket: DataTypes.TEXT,
    DryIR1_Vis: DataTypes.BOOLEAN,
    DryIR1_Stet: DataTypes.BOOLEAN,
    DryIR1_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR1_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR1_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR1_TempM: DataTypes.DECIMAL(5, 2),
    DryIR1_Ket: DataTypes.TEXT,
    DryIR2_Vis: DataTypes.BOOLEAN,
    DryIR2_Stet: DataTypes.BOOLEAN,
    DryIR2_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR2_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR2_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR2_TempM: DataTypes.DECIMAL(5, 2),
    DryIR2_Ket: DataTypes.TEXT,
    DryIR3_Vis: DataTypes.BOOLEAN,
    DryIR3_Stet: DataTypes.BOOLEAN,
    DryIR3_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR3_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR3_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR3_TempM: DataTypes.DECIMAL(5, 2),
    DryIR3_Ket: DataTypes.TEXT,
    DryIR4_Vis: DataTypes.BOOLEAN,
    DryIR4_Stet: DataTypes.BOOLEAN,
    DryIR4_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR4_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR4_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR4_TempM: DataTypes.DECIMAL(5, 2),
    DryIR4_Ket: DataTypes.TEXT,
    DryIR5_Vis: DataTypes.BOOLEAN,
    DryIR5_Stet: DataTypes.BOOLEAN,
    DryIR5_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR5_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR5_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR5_TempM: DataTypes.DECIMAL(5, 2),
    DryIR5_Ket: DataTypes.TEXT,
    DryIR6_Vis: DataTypes.BOOLEAN,
    DryIR6_Stet: DataTypes.BOOLEAN,
    DryIR6_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR6_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR6_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR6_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR6_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR6_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR6_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR6_TempM: DataTypes.DECIMAL(5, 2),
    DryIR6_Ket: DataTypes.TEXT,
    DryIR7_Vis: DataTypes.BOOLEAN,
    DryIR7_Stet: DataTypes.BOOLEAN,
    DryIR7_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR7_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR7_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR7_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR7_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR7_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR7_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR7_TempM: DataTypes.DECIMAL(5, 2),
    DryIR7_Ket: DataTypes.TEXT,
    DryIR8_Vis: DataTypes.BOOLEAN,
    DryIR8_Stet: DataTypes.BOOLEAN,
    DryIR8_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR8_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR8_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR8_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR8_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR8_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR8_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR8_TempM: DataTypes.DECIMAL(5, 2),
    DryIR8_Ket: DataTypes.TEXT,
    DryIR9_Vis: DataTypes.BOOLEAN,
    DryIR9_Stet: DataTypes.BOOLEAN,
    DryIR9_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR9_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR9_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR9_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR9_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR9_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR9_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR9_TempM: DataTypes.DECIMAL(5, 2),
    DryIR9_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_3_daily = db.define(
  "coating_3_daily",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    UnwA_Vis: DataTypes.BOOLEAN,
    UnwA_Stet: DataTypes.BOOLEAN,
    UnwA_ArusR: DataTypes.DECIMAL(5, 2),
    UnwA_ArusS: DataTypes.DECIMAL(5, 2),
    UnwA_ArusT: DataTypes.DECIMAL(5, 2),
    UnwA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwA_TempM: DataTypes.DECIMAL(5, 2),
    UnwA_Ket: DataTypes.TEXT,
    UnwB_Vis: DataTypes.BOOLEAN,
    UnwB_Stet: DataTypes.BOOLEAN,
    UnwB_ArusR: DataTypes.DECIMAL(5, 2),
    UnwB_ArusS: DataTypes.DECIMAL(5, 2),
    UnwB_ArusT: DataTypes.DECIMAL(5, 2),
    UnwB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwB_TempM: DataTypes.DECIMAL(5, 2),
    UnwB_Ket: DataTypes.TEXT,
    Inf1_Vis: DataTypes.BOOLEAN,
    Inf1_Stet: DataTypes.BOOLEAN,
    Inf1_ArusR: DataTypes.DECIMAL(5, 2),
    Inf1_ArusS: DataTypes.DECIMAL(5, 2),
    Inf1_ArusT: DataTypes.DECIMAL(5, 2),
    Inf1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Inf1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Inf1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Inf1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Inf1_TempM: DataTypes.DECIMAL(5, 2),
    Inf1_Ket: DataTypes.TEXT,
    PrmRol_Vis: DataTypes.BOOLEAN,
    PrmRol_Stet: DataTypes.BOOLEAN,
    PrmRol_ArusR: DataTypes.DECIMAL(5, 2),
    PrmRol_ArusS: DataTypes.DECIMAL(5, 2),
    PrmRol_ArusT: DataTypes.DECIMAL(5, 2),
    PrmRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    PrmRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    PrmRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    PrmRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    PrmRol_TempM: DataTypes.DECIMAL(5, 2),
    PrmRol_Ket: DataTypes.TEXT,
    VacRol1_Vis: DataTypes.BOOLEAN,
    VacRol1_Stet: DataTypes.BOOLEAN,
    VacRol1_ArusR: DataTypes.DECIMAL(5, 2),
    VacRol1_ArusS: DataTypes.DECIMAL(5, 2),
    VacRol1_ArusT: DataTypes.DECIMAL(5, 2),
    VacRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    VacRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    VacRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    VacRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    VacRol1_TempM: DataTypes.DECIMAL(5, 2),
    VacRol1_Ket: DataTypes.TEXT,
    OvnRol1_Vis: DataTypes.BOOLEAN,
    OvnRol1_Stet: DataTypes.BOOLEAN,
    OvnRol1_ArusR: DataTypes.DECIMAL(5, 2),
    OvnRol1_ArusS: DataTypes.DECIMAL(5, 2),
    OvnRol1_ArusT: DataTypes.DECIMAL(5, 2),
    OvnRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    OvnRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    OvnRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    OvnRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    OvnRol1_TempM: DataTypes.DECIMAL(5, 2),
    OvnRol1_Ket: DataTypes.TEXT,
    ChilRol1_Vis: DataTypes.BOOLEAN,
    ChilRol1_Stet: DataTypes.BOOLEAN,
    ChilRol1_ArusR: DataTypes.DECIMAL(5, 2),
    ChilRol1_ArusS: DataTypes.DECIMAL(5, 2),
    ChilRol1_ArusT: DataTypes.DECIMAL(5, 2),
    ChilRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ChilRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ChilRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ChilRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ChilRol1_TempM: DataTypes.DECIMAL(5, 2),
    ChilRol1_Ket: DataTypes.TEXT,
    Inf2_Vis: DataTypes.BOOLEAN,
    Inf2_Stet: DataTypes.BOOLEAN,
    Inf2_ArusR: DataTypes.DECIMAL(5, 2),
    Inf2_ArusS: DataTypes.DECIMAL(5, 2),
    Inf2_ArusT: DataTypes.DECIMAL(5, 2),
    Inf2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Inf2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Inf2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Inf2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Inf2_TempM: DataTypes.DECIMAL(5, 2),
    Inf2_Ket: DataTypes.TEXT,
    CoatRol_Vis: DataTypes.BOOLEAN,
    CoatRol_Stet: DataTypes.BOOLEAN,
    CoatRol_ArusR: DataTypes.DECIMAL(5, 2),
    CoatRol_ArusS: DataTypes.DECIMAL(5, 2),
    CoatRol_ArusT: DataTypes.DECIMAL(5, 2),
    CoatRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatRol_TempM: DataTypes.DECIMAL(5, 2),
    CoatRol_Ket: DataTypes.TEXT,
    VacRol2_Vis: DataTypes.BOOLEAN,
    VacRol2_Stet: DataTypes.BOOLEAN,
    VacRol2_ArusR: DataTypes.DECIMAL(5, 2),
    VacRol2_ArusS: DataTypes.DECIMAL(5, 2),
    VacRol2_ArusT: DataTypes.DECIMAL(5, 2),
    VacRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    VacRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    VacRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    VacRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    VacRol2_TempM: DataTypes.DECIMAL(5, 2),
    VacRol2_Ket: DataTypes.TEXT,
    OvnRol2_Vis: DataTypes.BOOLEAN,
    OvnRol2_Stet: DataTypes.BOOLEAN,
    OvnRol2_ArusR: DataTypes.DECIMAL(5, 2),
    OvnRol2_ArusS: DataTypes.DECIMAL(5, 2),
    OvnRol2_ArusT: DataTypes.DECIMAL(5, 2),
    OvnRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    OvnRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    OvnRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    OvnRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    OvnRol2_TempM: DataTypes.DECIMAL(5, 2),
    OvnRol2_Ket: DataTypes.TEXT,
    ChilRol2_Vis: DataTypes.BOOLEAN,
    ChilRol2_Stet: DataTypes.BOOLEAN,
    ChilRol2_ArusR: DataTypes.DECIMAL(5, 2),
    ChilRol2_ArusS: DataTypes.DECIMAL(5, 2),
    ChilRol2_ArusT: DataTypes.DECIMAL(5, 2),
    ChilRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ChilRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ChilRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ChilRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ChilRol2_TempM: DataTypes.DECIMAL(5, 2),
    ChilRol2_Ket: DataTypes.TEXT,
    TrcRol_Vis: DataTypes.BOOLEAN,
    TrcRol_Stet: DataTypes.BOOLEAN,
    TrcRol_ArusR: DataTypes.DECIMAL(5, 2),
    TrcRol_ArusS: DataTypes.DECIMAL(5, 2),
    TrcRol_ArusT: DataTypes.DECIMAL(5, 2),
    TrcRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    TrcRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    TrcRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    TrcRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    TrcRol_TempM: DataTypes.DECIMAL(5, 2),
    TrcRol_Ket: DataTypes.TEXT,
    TrcRol_Vis: DataTypes.BOOLEAN,
    TrcRol_Stet: DataTypes.BOOLEAN,
    TrcRol_ArusR: DataTypes.DECIMAL(5, 2),
    TrcRol_ArusS: DataTypes.DECIMAL(5, 2),
    TrcRol_ArusT: DataTypes.DECIMAL(5, 2),
    TrcRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    TrcRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    TrcRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    TrcRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    TrcRol_TempM: DataTypes.DECIMAL(5, 2),
    TrcRol_Ket: DataTypes.TEXT,
    RwdA_Vis: DataTypes.BOOLEAN,
    RwdA_Stet: DataTypes.BOOLEAN,
    RwdA_ArusR: DataTypes.DECIMAL(5, 2),
    RwdA_ArusS: DataTypes.DECIMAL(5, 2),
    RwdA_ArusT: DataTypes.DECIMAL(5, 2),
    RwdA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdA_TempM: DataTypes.DECIMAL(5, 2),
    RwdA_Ket: DataTypes.TEXT,
    RwdB_Vis: DataTypes.BOOLEAN,
    RwdB_Stet: DataTypes.BOOLEAN,
    RwdB_ArusR: DataTypes.DECIMAL(5, 2),
    RwdB_ArusS: DataTypes.DECIMAL(5, 2),
    RwdB_ArusT: DataTypes.DECIMAL(5, 2),
    RwdB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdB_TempM: DataTypes.DECIMAL(5, 2),
    RwdB_Ket: DataTypes.TEXT,
  },

  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_3_weekly = db.define(
  "coating_3_weekly",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    FanMtrUnwA_Vis: DataTypes.BOOLEAN,
    FanMtrUnwA_Stet: DataTypes.BOOLEAN,
    FanMtrUnwA_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_Ket: DataTypes.TEXT,
    FanMtrUnwB_Vis: DataTypes.BOOLEAN,
    FanMtrUnwB_Stet: DataTypes.BOOLEAN,
    FanMtrUnwB_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_Ket: DataTypes.TEXT,
    CorBlow_Vis: DataTypes.BOOLEAN,
    CorBlow_Stet: DataTypes.BOOLEAN,
    CorBlow_ArusR: DataTypes.DECIMAL(5, 2),
    CorBlow_ArusS: DataTypes.DECIMAL(5, 2),
    CorBlow_ArusT: DataTypes.DECIMAL(5, 2),
    CorBlow_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CorBlow_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CorBlow_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CorBlow_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CorBlow_TempM: DataTypes.DECIMAL(5, 2),
    CorBlow_Ket: DataTypes.TEXT,
    FanMtrInf1_Vis: DataTypes.BOOLEAN,
    FanMtrInf1_Stet: DataTypes.BOOLEAN,
    FanMtrInf1_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrInf1_Ket: DataTypes.TEXT,
    FanMtrPrmRol_Vis: DataTypes.BOOLEAN,
    FanMtrPrmRol_Stet: DataTypes.BOOLEAN,
    FanMtrPrmRol_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrPrmRol_Ket: DataTypes.TEXT,
    FanMtrVacRol1_Vis: DataTypes.BOOLEAN,
    FanMtrVacRol1_Stet: DataTypes.BOOLEAN,
    FanMtrVacRol1_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol1_Ket: DataTypes.TEXT,
    FanMtrOvnRol1_Vis: DataTypes.BOOLEAN,
    FanMtrOvnRol1_Stet: DataTypes.BOOLEAN,
    FanMtrOvnRol1_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol1_Ket: DataTypes.TEXT,
    FanMtrChil1_Vis: DataTypes.BOOLEAN,
    FanMtrChil1_Stet: DataTypes.BOOLEAN,
    FanMtrChil1_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrChil1_Ket: DataTypes.TEXT,
    FanMtrInf2_Vis: DataTypes.BOOLEAN,
    FanMtrInf2_Stet: DataTypes.BOOLEAN,
    FanMtrInf2_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrInf2_Ket: DataTypes.TEXT,
    FanMtrCoatRol_Vis: DataTypes.BOOLEAN,
    FanMtrCoatRol_Stet: DataTypes.BOOLEAN,
    FanMtrCoatRol_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrCoatRol_Ket: DataTypes.TEXT,
    FanMtrVacRol2_Vis: DataTypes.BOOLEAN,
    FanMtrVacRol2_Stet: DataTypes.BOOLEAN,
    FanMtrVacRol2_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrVacRol2_Ket: DataTypes.TEXT,
    FanMtrOvnRol2_Vis: DataTypes.BOOLEAN,
    FanMtrOvnRol2_Stet: DataTypes.BOOLEAN,
    FanMtrOvnRol2_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrOvnRol2_Ket: DataTypes.TEXT,
    FanMtrChil2_Vis: DataTypes.BOOLEAN,
    FanMtrChil2_Stet: DataTypes.BOOLEAN,
    FanMtrChil2_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrChil2_Ket: DataTypes.TEXT,
    FanMtrTrcRol_Vis: DataTypes.BOOLEAN,
    FanMtrTrcRol_Stet: DataTypes.BOOLEAN,
    FanMtrTrcRol_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrTrcRol_Ket: DataTypes.TEXT,
    FanMtrRwdA_Vis: DataTypes.BOOLEAN,
    FanMtrRwdA_Stet: DataTypes.BOOLEAN,
    FanMtrRwdA_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_Ket: DataTypes.TEXT,
    FanMtrRwdB_Vis: DataTypes.BOOLEAN,
    FanMtrRwdB_Stet: DataTypes.BOOLEAN,
    FanMtrRwdB_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_Ket: DataTypes.TEXT,
    ExhIR2_Vis: DataTypes.BOOLEAN,
    ExhIR2_Stet: DataTypes.BOOLEAN,
    ExhIR2_ArusR: DataTypes.DECIMAL(5, 2),
    ExhIR2_ArusS: DataTypes.DECIMAL(5, 2),
    ExhIR2_ArusT: DataTypes.DECIMAL(5, 2),
    ExhIR2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhIR2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhIR2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhIR2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhIR2_TempM: DataTypes.DECIMAL(5, 2),
    ExhIR2_Ket: DataTypes.TEXT,
    Blw1IR2_Vis: DataTypes.BOOLEAN,
    Blw1IR2_Stet: DataTypes.BOOLEAN,
    Blw1IR2_ArusR: DataTypes.DECIMAL(5, 2),
    Blw1IR2_ArusS: DataTypes.DECIMAL(5, 2),
    Blw1IR2_ArusT: DataTypes.DECIMAL(5, 2),
    Blw1IR2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw1IR2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw1IR2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw1IR2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw1IR2_TempM: DataTypes.DECIMAL(5, 2),
    Blw1IR2_Ket: DataTypes.TEXT,
    Blw2IR2_Vis: DataTypes.BOOLEAN,
    Blw2IR2_Stet: DataTypes.BOOLEAN,
    Blw2IR2_ArusR: DataTypes.DECIMAL(5, 2),
    Blw2IR2_ArusS: DataTypes.DECIMAL(5, 2),
    Blw2IR2_ArusT: DataTypes.DECIMAL(5, 2),
    Blw2IR2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw2IR2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw2IR2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw2IR2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw2IR2_TempM: DataTypes.DECIMAL(5, 2),
    Blw2IR2_Ket: DataTypes.TEXT,
    Ovn1Blow1_Vis: DataTypes.BOOLEAN,
    Ovn1Blow1_Stet: DataTypes.BOOLEAN,
    Ovn1Blow1_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_TempM: DataTypes.DECIMAL(5, 2),
    Ovn1Blow1_Ket: DataTypes.TEXT,
    Ovn1Blow2_Vis: DataTypes.BOOLEAN,
    Ovn1Blow2_Stet: DataTypes.BOOLEAN,
    Ovn1Blow2_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_TempM: DataTypes.DECIMAL(5, 2),
    Ovn1Blow2_Ket: DataTypes.TEXT,
    Ovn1Blow3_Vis: DataTypes.BOOLEAN,
    Ovn1Blow3_Stet: DataTypes.BOOLEAN,
    Ovn1Blow3_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_TempM: DataTypes.DECIMAL(5, 2),
    Ovn1Blow3_Ket: DataTypes.TEXT,
    Ovn1Blow4_Vis: DataTypes.BOOLEAN,
    Ovn1Blow4_Stet: DataTypes.BOOLEAN,
    Ovn1Blow4_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_TempM: DataTypes.DECIMAL(5, 2),
    Ovn1Blow4_Ket: DataTypes.TEXT,
    Ovn1Blow5_Vis: DataTypes.BOOLEAN,
    Ovn1Blow5_Stet: DataTypes.BOOLEAN,
    Ovn1Blow5_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_TempM: DataTypes.DECIMAL(5, 2),
    Ovn1Blow5_Ket: DataTypes.TEXT,
    Ovn2Blow1_Vis: DataTypes.BOOLEAN,
    Ovn2Blow1_Stet: DataTypes.BOOLEAN,
    Ovn2Blow1_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_TempM: DataTypes.DECIMAL(5, 2),
    Ovn2Blow1_Ket: DataTypes.TEXT,
    Ovn2Blow2_Vis: DataTypes.BOOLEAN,
    Ovn2Blow2_Stet: DataTypes.BOOLEAN,
    Ovn2Blow2_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_TempM: DataTypes.DECIMAL(5, 2),
    Ovn2Blow2_Ket: DataTypes.TEXT,
    Ovn2Blow3_Vis: DataTypes.BOOLEAN,
    Ovn2Blow3_Stet: DataTypes.BOOLEAN,
    Ovn2Blow3_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_TempM: DataTypes.DECIMAL(5, 2),
    Ovn2Blow3_Ket: DataTypes.TEXT,
    Ovn2Blow4_Vis: DataTypes.BOOLEAN,
    Ovn2Blow4_Stet: DataTypes.BOOLEAN,
    Ovn2Blow4_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_TempM: DataTypes.DECIMAL(5, 2),
    Ovn2Blow4_Ket: DataTypes.TEXT,
    Ovn2Blow5_Vis: DataTypes.BOOLEAN,
    Ovn2Blow5_Stet: DataTypes.BOOLEAN,
    Ovn2Blow5_ArusR: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_ArusS: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_ArusT: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_TempM: DataTypes.DECIMAL(5, 2),
    Ovn2Blow5_Ket: DataTypes.TEXT,
    VerPmpPrim_Vis: DataTypes.BOOLEAN,
    VerPmpPrim_Stet: DataTypes.BOOLEAN,
    VerPmpPrim_ArusR: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_ArusS: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_ArusT: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_VDE_Vms: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_VDE_Vge: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_TempM: DataTypes.DECIMAL(5, 2),
    VerPmpPrim_Ket: DataTypes.TEXT,
    VerPmpCoat_Vis: DataTypes.BOOLEAN,
    VerPmpCoat_Stet: DataTypes.BOOLEAN,
    VerPmpCoat_ArusR: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_ArusS: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_ArusT: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_VDE_Vms: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_VDE_Vge: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_TempM: DataTypes.DECIMAL(5, 2),
    VerPmpCoat_Ket: DataTypes.TEXT,
    MixSilCoat_Vis: DataTypes.BOOLEAN,
    MixSilCoat_Stet: DataTypes.BOOLEAN,
    MixSilCoat_ArusR: DataTypes.DECIMAL(5, 2),
    MixSilCoat_ArusS: DataTypes.DECIMAL(5, 2),
    MixSilCoat_ArusT: DataTypes.DECIMAL(5, 2),
    MixSilCoat_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MixSilCoat_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MixSilCoat_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MixSilCoat_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MixSilCoat_TempM: DataTypes.DECIMAL(5, 2),
    MixSilCoat_Ket: DataTypes.TEXT,
    ExhVac1_Vis: DataTypes.BOOLEAN,
    ExhVac1_Stet: DataTypes.BOOLEAN,
    ExhVac1_ArusR: DataTypes.DECIMAL(5, 2),
    ExhVac1_ArusS: DataTypes.DECIMAL(5, 2),
    ExhVac1_ArusT: DataTypes.DECIMAL(5, 2),
    ExhVac1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhVac1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhVac1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhVac1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhVac1_TempM: DataTypes.DECIMAL(5, 2),
    ExhVac1_Ket: DataTypes.TEXT,
    ExhVac2_Vis: DataTypes.BOOLEAN,
    ExhVac2_Stet: DataTypes.BOOLEAN,
    ExhVac2_ArusR: DataTypes.DECIMAL(5, 2),
    ExhVac2_ArusS: DataTypes.DECIMAL(5, 2),
    ExhVac2_ArusT: DataTypes.DECIMAL(5, 2),
    ExhVac2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhVac2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhVac2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhVac2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhVac2_TempM: DataTypes.DECIMAL(5, 2),
    ExhVac2_Ket: DataTypes.TEXT,
    ExhOvn1_Vis: DataTypes.BOOLEAN,
    ExhOvn1_Stet: DataTypes.BOOLEAN,
    ExhOvn1_ArusR: DataTypes.DECIMAL(5, 2),
    ExhOvn1_ArusS: DataTypes.DECIMAL(5, 2),
    ExhOvn1_ArusT: DataTypes.DECIMAL(5, 2),
    ExhOvn1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhOvn1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhOvn1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhOvn1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhOvn1_TempM: DataTypes.DECIMAL(5, 2),
    ExhOvn1_Ket: DataTypes.TEXT,
    ExhOvn2_Vis: DataTypes.BOOLEAN,
    ExhOvn2_Stet: DataTypes.BOOLEAN,
    ExhOvn2_ArusR: DataTypes.DECIMAL(5, 2),
    ExhOvn2_ArusS: DataTypes.DECIMAL(5, 2),
    ExhOvn2_ArusT: DataTypes.DECIMAL(5, 2),
    ExhOvn2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhOvn2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhOvn2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ExhOvn2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ExhOvn2_TempM: DataTypes.DECIMAL(5, 2),
    ExhOvn2_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_3_monthly = db.define(
  "coating_3_monthly",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    UwdTur_Vis: DataTypes.BOOLEAN,
    UwdTur_Stet: DataTypes.BOOLEAN,
    UwdTur_ArusR: DataTypes.DECIMAL(5, 2),
    UwdTur_ArusS: DataTypes.DECIMAL(5, 2),
    UwdTur_ArusT: DataTypes.DECIMAL(5, 2),
    UwdTur_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UwdTur_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UwdTur_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UwdTur_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UwdTur_TempM: DataTypes.DECIMAL(5, 2),
    UwdTur_Ket: DataTypes.TEXT,
    RwdTur_Vis: DataTypes.BOOLEAN,
    RwdTur_Stet: DataTypes.BOOLEAN,
    RwdTur_ArusR: DataTypes.DECIMAL(5, 2),
    RwdTur_ArusS: DataTypes.DECIMAL(5, 2),
    RwdTur_ArusT: DataTypes.DECIMAL(5, 2),
    RwdTur_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdTur_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdTur_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdTur_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdTur_TempM: DataTypes.DECIMAL(5, 2),
    RwdTur_Ket: DataTypes.TEXT,
    MtrOsc1_Vis: DataTypes.BOOLEAN,
    MtrOsc1_Stet: DataTypes.BOOLEAN,
    MtrOsc1_ArusR: DataTypes.DECIMAL(5, 2),
    MtrOsc1_ArusS: DataTypes.DECIMAL(5, 2),
    MtrOsc1_ArusT: DataTypes.DECIMAL(5, 2),
    MtrOsc1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrOsc1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrOsc1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrOsc1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrOsc1_TempM: DataTypes.DECIMAL(5, 2),
    MtrOsc1_Ket: DataTypes.TEXT,
    MtrOsc2_Vis: DataTypes.BOOLEAN,
    MtrOsc2_Stet: DataTypes.BOOLEAN,
    MtrOsc2_ArusR: DataTypes.DECIMAL(5, 2),
    MtrOsc2_ArusS: DataTypes.DECIMAL(5, 2),
    MtrOsc2_ArusT: DataTypes.DECIMAL(5, 2),
    MtrOsc2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrOsc2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrOsc2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrOsc2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrOsc2_TempM: DataTypes.DECIMAL(5, 2),
    MtrOsc2_Ket: DataTypes.TEXT,
    ElecCor_Vis: DataTypes.BOOLEAN,
    ElecCor_Stet: DataTypes.BOOLEAN,
    ElecCor_ArusR: DataTypes.DECIMAL(5, 2),
    ElecCor_ArusS: DataTypes.DECIMAL(5, 2),
    ElecCor_ArusT: DataTypes.DECIMAL(5, 2),
    ElecCor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ElecCor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ElecCor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ElecCor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ElecCor_TempM: DataTypes.DECIMAL(5, 2),
    ElecCor_Ket: DataTypes.TEXT,
    DryIR_Vis: DataTypes.BOOLEAN,
    DryIR_Stet: DataTypes.BOOLEAN,
    DryIR_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR_TempM: DataTypes.DECIMAL(5, 2),
    DryIR_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_4_daily = db.define(
  "coating_4_daily",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    UnwA_Vis: DataTypes.BOOLEAN,
    UnwA_Stet: DataTypes.BOOLEAN,
    UnwA_ArusR: DataTypes.DECIMAL(5, 2),
    UnwA_ArusS: DataTypes.DECIMAL(5, 2),
    UnwA_ArusT: DataTypes.DECIMAL(5, 2),
    UnwA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwA_TempM: DataTypes.DECIMAL(5, 2),
    UnwA_Ket: DataTypes.TEXT,
    UnwB_Vis: DataTypes.BOOLEAN,
    UnwB_Stet: DataTypes.BOOLEAN,
    UnwB_ArusR: DataTypes.DECIMAL(5, 2),
    UnwB_ArusS: DataTypes.DECIMAL(5, 2),
    UnwB_ArusT: DataTypes.DECIMAL(5, 2),
    UnwB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UnwB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UnwB_TempM: DataTypes.DECIMAL(5, 2),
    UnwB_Ket: DataTypes.TEXT,
    InfCor_Vis: DataTypes.BOOLEAN,
    InfCor_Stet: DataTypes.BOOLEAN,
    InfCor_ArusR: DataTypes.DECIMAL(5, 2),
    InfCor_ArusS: DataTypes.DECIMAL(5, 2),
    InfCor_ArusT: DataTypes.DECIMAL(5, 2),
    InfCor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    InfCor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    InfCor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    InfCor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    InfCor_TempM: DataTypes.DECIMAL(5, 2),
    InfCor_Ket: DataTypes.TEXT,
    Exp1_Vis: DataTypes.BOOLEAN,
    Exp1_Stet: DataTypes.BOOLEAN,
    Exp1_ArusR: DataTypes.DECIMAL(5, 2),
    Exp1_ArusS: DataTypes.DECIMAL(5, 2),
    Exp1_ArusT: DataTypes.DECIMAL(5, 2),
    Exp1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exp1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exp1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exp1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exp1_TempM: DataTypes.DECIMAL(5, 2),
    Exp1_Ket: DataTypes.TEXT,
    GrvRolPrm_Vis: DataTypes.BOOLEAN,
    GrvRolPrm_Stet: DataTypes.BOOLEAN,
    GrvRolPrm_ArusR: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_ArusS: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_ArusT: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VDE_Vms: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VDE_Vge: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_TempM: DataTypes.DECIMAL(5, 2),
    GrvRolPrm_Ket: DataTypes.TEXT,
    Ofd1_Vis: DataTypes.BOOLEAN,
    Ofd1_Stet: DataTypes.BOOLEAN,
    Ofd1_ArusR: DataTypes.DECIMAL(5, 2),
    Ofd1_ArusS: DataTypes.DECIMAL(5, 2),
    Ofd1_ArusT: DataTypes.DECIMAL(5, 2),
    Ofd1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ofd1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ofd1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ofd1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ofd1_TempM: DataTypes.DECIMAL(5, 2),
    Ofd1_Ket: DataTypes.TEXT,
    GrvRolLtx_Vis: DataTypes.BOOLEAN,
    GrvRolLtx_Stet: DataTypes.BOOLEAN,
    GrvRolLtx_ArusR: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_ArusS: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_ArusT: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_VDE_Vms: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_VDE_Vge: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_TempM: DataTypes.DECIMAL(5, 2),
    GrvRolLtx_Ket: DataTypes.TEXT,
    Exp2_Vis: DataTypes.BOOLEAN,
    Exp2_Stet: DataTypes.BOOLEAN,
    Exp2_ArusR: DataTypes.DECIMAL(5, 2),
    Exp2_ArusS: DataTypes.DECIMAL(5, 2),
    Exp2_ArusT: DataTypes.DECIMAL(5, 2),
    Exp2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exp2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exp2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exp2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exp2_TempM: DataTypes.DECIMAL(5, 2),
    Exp2_Ket: DataTypes.TEXT,
    SucRol_Vis: DataTypes.BOOLEAN,
    SucRol_Stet: DataTypes.BOOLEAN,
    SucRol_ArusR: DataTypes.DECIMAL(5, 2),
    SucRol_ArusS: DataTypes.DECIMAL(5, 2),
    SucRol_ArusT: DataTypes.DECIMAL(5, 2),
    SucRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    SucRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    SucRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    SucRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    SucRol_TempM: DataTypes.DECIMAL(5, 2),
    SucRol_Ket: DataTypes.TEXT,
    Ofd2_Vis: DataTypes.BOOLEAN,
    Ofd2_Stet: DataTypes.BOOLEAN,
    Ofd2_ArusR: DataTypes.DECIMAL(5, 2),
    Ofd2_ArusS: DataTypes.DECIMAL(5, 2),
    Ofd2_ArusT: DataTypes.DECIMAL(5, 2),
    Ofd2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Ofd2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Ofd2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Ofd2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Ofd2_TempM: DataTypes.DECIMAL(5, 2),
    Ofd2_Ket: DataTypes.TEXT,
    RwdA_Vis: DataTypes.BOOLEAN,
    RwdA_Stet: DataTypes.BOOLEAN,
    RwdA_ArusR: DataTypes.DECIMAL(5, 2),
    RwdA_ArusS: DataTypes.DECIMAL(5, 2),
    RwdA_ArusT: DataTypes.DECIMAL(5, 2),
    RwdA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdA_TempM: DataTypes.DECIMAL(5, 2),
    RwdA_Ket: DataTypes.TEXT,
    RwdB_Vis: DataTypes.BOOLEAN,
    RwdB_Stet: DataTypes.BOOLEAN,
    RwdB_ArusR: DataTypes.DECIMAL(5, 2),
    RwdB_ArusS: DataTypes.DECIMAL(5, 2),
    RwdB_ArusT: DataTypes.DECIMAL(5, 2),
    RwdB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdB_TempM: DataTypes.DECIMAL(5, 2),
    RwdB_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_4_weekly = db.define(
  "coating_4_weekly",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    FanMtrUnwA_Vis: DataTypes.BOOLEAN,
    FanMtrUnwA_Stet: DataTypes.BOOLEAN,
    FanMtrUnwA_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrUnwA_Ket: DataTypes.TEXT,
    FanMtrUnwB_Vis: DataTypes.BOOLEAN,
    FanMtrUnwB_Stet: DataTypes.BOOLEAN,
    FanMtrUnwB_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrUnwB_Ket: DataTypes.TEXT,
    FanMtrRwdA_Vis: DataTypes.BOOLEAN,
    FanMtrRwdA_Stet: DataTypes.BOOLEAN,
    FanMtrRwdA_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrRwdA_Ket: DataTypes.TEXT,
    FanMtrRwdB_Vis: DataTypes.BOOLEAN,
    FanMtrRwdB_Stet: DataTypes.BOOLEAN,
    FanMtrRwdB_ArusR: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_ArusS: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_ArusT: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_TempM: DataTypes.DECIMAL(5, 2),
    FanMtrRwdB_Ket: DataTypes.TEXT,
    CorBlow_Vis: DataTypes.BOOLEAN,
    CorBlow_Stet: DataTypes.BOOLEAN,
    CorBlow_ArusR: DataTypes.DECIMAL(5, 2),
    CorBlow_ArusS: DataTypes.DECIMAL(5, 2),
    CorBlow_ArusT: DataTypes.DECIMAL(5, 2),
    CorBlow_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CorBlow_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CorBlow_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CorBlow_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CorBlow_TempM: DataTypes.DECIMAL(5, 2),
    CorBlow_Ket: DataTypes.TEXT,
    Dry1_Vis: DataTypes.BOOLEAN,
    Dry1_Stet: DataTypes.BOOLEAN,
    Dry1_ArusR: DataTypes.DECIMAL(5, 2),
    Dry1_ArusS: DataTypes.DECIMAL(5, 2),
    Dry1_ArusT: DataTypes.DECIMAL(5, 2),
    Dry1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1_TempM: DataTypes.DECIMAL(5, 2),
    Dry1_Ket: DataTypes.TEXT,
    Dry2_Vis: DataTypes.BOOLEAN,
    Dry2_Stet: DataTypes.BOOLEAN,
    Dry2_ArusR: DataTypes.DECIMAL(5, 2),
    Dry2_ArusS: DataTypes.DECIMAL(5, 2),
    Dry2_ArusT: DataTypes.DECIMAL(5, 2),
    Dry2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry2_TempM: DataTypes.DECIMAL(5, 2),
    Dry2_Ket: DataTypes.TEXT,
    Dry3_Vis: DataTypes.BOOLEAN,
    Dry3_Stet: DataTypes.BOOLEAN,
    Dry3_ArusR: DataTypes.DECIMAL(5, 2),
    Dry3_ArusS: DataTypes.DECIMAL(5, 2),
    Dry3_ArusT: DataTypes.DECIMAL(5, 2),
    Dry3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry3_TempM: DataTypes.DECIMAL(5, 2),
    Dry3_Ket: DataTypes.TEXT,
    Dry4_Vis: DataTypes.BOOLEAN,
    Dry4_Stet: DataTypes.BOOLEAN,
    Dry4_ArusR: DataTypes.DECIMAL(5, 2),
    Dry4_ArusS: DataTypes.DECIMAL(5, 2),
    Dry4_ArusT: DataTypes.DECIMAL(5, 2),
    Dry4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry4_TempM: DataTypes.DECIMAL(5, 2),
    Dry4_Ket: DataTypes.TEXT,
    Dry5_Vis: DataTypes.BOOLEAN,
    Dry5_Stet: DataTypes.BOOLEAN,
    Dry5_ArusR: DataTypes.DECIMAL(5, 2),
    Dry5_ArusS: DataTypes.DECIMAL(5, 2),
    Dry5_ArusT: DataTypes.DECIMAL(5, 2),
    Dry5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry5_TempM: DataTypes.DECIMAL(5, 2),
    Dry5_Ket: DataTypes.TEXT,
    Dry6_Vis: DataTypes.BOOLEAN,
    Dry6_Stet: DataTypes.BOOLEAN,
    Dry6_ArusR: DataTypes.DECIMAL(5, 2),
    Dry6_ArusS: DataTypes.DECIMAL(5, 2),
    Dry6_ArusT: DataTypes.DECIMAL(5, 2),
    Dry6_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry6_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry6_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry6_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry6_TempM: DataTypes.DECIMAL(5, 2),
    Dry6_Ket: DataTypes.TEXT,
    Dry7_Vis: DataTypes.BOOLEAN,
    Dry7_Stet: DataTypes.BOOLEAN,
    Dry7_ArusR: DataTypes.DECIMAL(5, 2),
    Dry7_ArusS: DataTypes.DECIMAL(5, 2),
    Dry7_ArusT: DataTypes.DECIMAL(5, 2),
    Dry7_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry7_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry7_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry7_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry7_TempM: DataTypes.DECIMAL(5, 2),
    Dry7_Ket: DataTypes.TEXT,
    Dry1_2_Vis: DataTypes.BOOLEAN,
    Dry1_2_Stet: DataTypes.BOOLEAN,
    Dry1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Dry1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Dry1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Dry1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry1_2_TempM: DataTypes.DECIMAL(5, 2),
    Dry1_2_Ket: DataTypes.TEXT,
    Dry3_4_Vis: DataTypes.BOOLEAN,
    Dry3_4_Stet: DataTypes.BOOLEAN,
    Dry3_4_ArusR: DataTypes.DECIMAL(5, 2),
    Dry3_4_ArusS: DataTypes.DECIMAL(5, 2),
    Dry3_4_ArusT: DataTypes.DECIMAL(5, 2),
    Dry3_4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry3_4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry3_4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry3_4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry3_4_TempM: DataTypes.DECIMAL(5, 2),
    Dry3_4_Ket: DataTypes.TEXT,
    Dry5_7_Vis: DataTypes.BOOLEAN,
    Dry5_7_Stet: DataTypes.BOOLEAN,
    Dry5_7_ArusR: DataTypes.DECIMAL(5, 2),
    Dry5_7_ArusS: DataTypes.DECIMAL(5, 2),
    Dry5_7_ArusT: DataTypes.DECIMAL(5, 2),
    Dry5_7_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry5_7_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry5_7_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dry5_7_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dry5_7_TempM: DataTypes.DECIMAL(5, 2),
    Dry5_7_Ket: DataTypes.TEXT,
    CoatOtfSuc_Vis: DataTypes.BOOLEAN,
    CoatOtfSuc_Stet: DataTypes.BOOLEAN,
    CoatOtfSuc_ArusR: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_ArusS: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_ArusT: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_TempM: DataTypes.DECIMAL(5, 2),
    CoatOtfSuc_Ket: DataTypes.TEXT,
    CoatOsc1_Vis: DataTypes.BOOLEAN,
    CoatOsc1_Stet: DataTypes.BOOLEAN,
    CoatOsc1_ArusR: DataTypes.DECIMAL(5, 2),
    CoatOsc1_ArusS: DataTypes.DECIMAL(5, 2),
    CoatOsc1_ArusT: DataTypes.DECIMAL(5, 2),
    CoatOsc1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatOsc1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatOsc1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatOsc1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatOsc1_TempM: DataTypes.DECIMAL(5, 2),
    CoatOsc1_Ket: DataTypes.TEXT,
    CoatOsc2_Vis: DataTypes.BOOLEAN,
    CoatOsc2_Stet: DataTypes.BOOLEAN,
    CoatOsc2_ArusR: DataTypes.DECIMAL(5, 2),
    CoatOsc2_ArusS: DataTypes.DECIMAL(5, 2),
    CoatOsc2_ArusT: DataTypes.DECIMAL(5, 2),
    CoatOsc2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatOsc2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatOsc2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatOsc2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatOsc2_TempM: DataTypes.DECIMAL(5, 2),
    CoatOsc2_Ket: DataTypes.TEXT,
    CoatPmpPrm_Vis: DataTypes.BOOLEAN,
    CoatPmpPrm_Stet: DataTypes.BOOLEAN,
    CoatPmpPrm_ArusR: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_ArusS: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_ArusT: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_TempM: DataTypes.DECIMAL(5, 2),
    CoatPmpPrm_Ket: DataTypes.TEXT,
    CoatPmpLtx1_Vis: DataTypes.BOOLEAN,
    CoatPmpLtx1_Stet: DataTypes.BOOLEAN,
    CoatPmpLtx1_ArusR: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_ArusS: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_ArusT: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_TempM: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx1_Ket: DataTypes.TEXT,
    CoatPmpLtx2_Vis: DataTypes.BOOLEAN,
    CoatPmpLtx2_Stet: DataTypes.BOOLEAN,
    CoatPmpLtx2_ArusR: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_ArusS: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_ArusT: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_TempM: DataTypes.DECIMAL(5, 2),
    CoatPmpLtx2_Ket: DataTypes.TEXT,
    MixSilCoatLtx_Vis: DataTypes.BOOLEAN,
    MixSilCoatLtx_Stet: DataTypes.BOOLEAN,
    MixSilCoatLtx_ArusR: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_ArusS: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_ArusT: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_TempM: DataTypes.DECIMAL(5, 2),
    MixSilCoatLtx_Ket: DataTypes.TEXT,
    RwdNearRol_Vis: DataTypes.BOOLEAN,
    RwdNearRol_Stet: DataTypes.BOOLEAN,
    RwdNearRol_ArusR: DataTypes.DECIMAL(5, 2),
    RwdNearRol_ArusS: DataTypes.DECIMAL(5, 2),
    RwdNearRol_ArusT: DataTypes.DECIMAL(5, 2),
    RwdNearRol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdNearRol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdNearRol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdNearRol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdNearRol_TempM: DataTypes.DECIMAL(5, 2),
    RwdNearRol_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const coating_4_monthly = db.define(
  "coating_4_monthly",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    UwdTur_Vis: DataTypes.BOOLEAN,
    UwdTur_Stet: DataTypes.BOOLEAN,
    UwdTur_ArusR: DataTypes.DECIMAL(5, 2),
    UwdTur_ArusS: DataTypes.DECIMAL(5, 2),
    UwdTur_ArusT: DataTypes.DECIMAL(5, 2),
    UwdTur_VDE_Vms: DataTypes.DECIMAL(5, 2),
    UwdTur_VDE_Vge: DataTypes.DECIMAL(5, 2),
    UwdTur_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    UwdTur_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    UwdTur_TempM: DataTypes.DECIMAL(5, 2),
    UwdTur_Ket: DataTypes.TEXT,
    RwdTur_Vis: DataTypes.BOOLEAN,
    RwdTur_Stet: DataTypes.BOOLEAN,
    RwdTur_ArusR: DataTypes.DECIMAL(5, 2),
    RwdTur_ArusS: DataTypes.DECIMAL(5, 2),
    RwdTur_ArusT: DataTypes.DECIMAL(5, 2),
    RwdTur_VDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdTur_VDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdTur_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    RwdTur_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    RwdTur_TempM: DataTypes.DECIMAL(5, 2),
    RwdTur_Ket: DataTypes.TEXT,
    MtrPmpEdgeGuiUW_Vis: DataTypes.BOOLEAN,
    MtrPmpEdgeGuiUW_Stet: DataTypes.BOOLEAN,
    MtrPmpEdgeGuiUW_ArusR: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_ArusS: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_ArusT: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_TempM: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiUW_Ket: DataTypes.TEXT,
    MtrPmpEdgeGuiRW_Vis: DataTypes.BOOLEAN,
    MtrPmpEdgeGuiRW_Stet: DataTypes.BOOLEAN,
    MtrPmpEdgeGuiRW_ArusR: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_ArusS: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_ArusT: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_VDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_VDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_TempM: DataTypes.DECIMAL(5, 2),
    MtrPmpEdgeGuiRW_Ket: DataTypes.TEXT,
    ElecCor_Vis: DataTypes.BOOLEAN,
    ElecCor_Stet: DataTypes.BOOLEAN,
    ElecCor_ArusR: DataTypes.DECIMAL(5, 2),
    ElecCor_ArusS: DataTypes.DECIMAL(5, 2),
    ElecCor_ArusT: DataTypes.DECIMAL(5, 2),
    ElecCor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    ElecCor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    ElecCor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    ElecCor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    ElecCor_TempM: DataTypes.DECIMAL(5, 2),
    ElecCor_Ket: DataTypes.TEXT,
    DryIR_Vis: DataTypes.BOOLEAN,
    DryIR_Stet: DataTypes.BOOLEAN,
    DryIR_ArusR: DataTypes.DECIMAL(5, 2),
    DryIR_ArusS: DataTypes.DECIMAL(5, 2),
    DryIR_ArusT: DataTypes.DECIMAL(5, 2),
    DryIR_VDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR_VDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    DryIR_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    DryIR_TempM: DataTypes.DECIMAL(5, 2),
    DryIR_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
module.exports = {
  //getAlluser,
  coating_1_daily,
  coating_1_weekly,
  coating_1_monthly,
  coating_3_daily,
  coating_3_weekly,
  coating_3_monthly,
  coating_4_daily,
  coating_4_weekly,
  coating_4_monthly,
}(async () => {
  await db.sync();
})();
