const { Sequelize, DataTypes } = require("sequelize");
const db = require("../config/Dbconnect.js");

const line_4_casting = db.define(
  "line_4_casting",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Chr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_TempM: DataTypes.DECIMAL(5, 2),
    Chr_ArusR: DataTypes.DECIMAL(5, 2),
    Chr_ArusS: DataTypes.DECIMAL(5, 2),
    Chr_ArusT: DataTypes.DECIMAL(5, 2),
    Chr_Ket: DataTypes.TEXT,
    Fan_Chr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Chr_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Chr_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Chr_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Chr_Ket: DataTypes.TEXT,
    Chr_Pum_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_TempM: DataTypes.DECIMAL(5, 2),
    Chr_Pum_ArusR: DataTypes.DECIMAL(5, 2),
    Chr_Pum_ArusS: DataTypes.DECIMAL(5, 2),
    Chr_Pum_ArusT: DataTypes.DECIMAL(5, 2),
    Chr_Pum_Ket: DataTypes.TEXT,
    Col_Die_Blt_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_TempM: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_ArusR: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_ArusS: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_ArusT: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_Ket: DataTypes.TEXT,
    Air_Knf_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Air_Knf_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Air_Knf_TempM: DataTypes.DECIMAL(5, 2),
    Air_Knf_ArusR: DataTypes.DECIMAL(5, 2),
    Air_Knf_ArusS: DataTypes.DECIMAL(5, 2),
    Air_Knf_ArusT: DataTypes.DECIMAL(5, 2),
    Air_Knf_Ket: DataTypes.TEXT,
    Wtr_Rmv_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_TempM: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusR: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusS: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusT: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_Ket: DataTypes.TEXT,
    Chr_Wtr_Bth_Pum_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_TempM: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_ArusR: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_ArusS: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_ArusT: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_4_ext = db.define(
  "line_4_ext",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Main_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Main_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Main_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Main_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Main_Ext_Ket: DataTypes.TEXT,
    Fan_Main_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_Ket: DataTypes.TEXT,
    Metering_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Metering_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Metering_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Metering_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Ket: DataTypes.TEXT,
    Fan_Metering_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Metering_Ext_Ket: DataTypes.TEXT,
    Co_Ext1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_TempM: DataTypes.DECIMAL(5, 2),
    Co_Ext1_ArusR: DataTypes.DECIMAL(5, 2),
    Co_Ext1_ArusS: DataTypes.DECIMAL(5, 2),
    Co_Ext1_ArusT: DataTypes.DECIMAL(5, 2),
    Co_Ext1_Ket: DataTypes.TEXT,
    Co_Ext2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_TempM: DataTypes.DECIMAL(5, 2),
    Co_Ext2_ArusR: DataTypes.DECIMAL(5, 2),
    Co_Ext2_ArusS: DataTypes.DECIMAL(5, 2),
    Co_Ext2_ArusT: DataTypes.DECIMAL(5, 2),
    Co_Ext2_Ket: DataTypes.TEXT,
    Fan_Co_Ext1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_Ket: DataTypes.TEXT,
    Fan_Co_Ext2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_Ket: DataTypes.TEXT,
    Main_Ext_Gea_Oil_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_TempM: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_ArusR: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_ArusS: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_ArusT: DataTypes.DECIMAL(5, 2),
    Main_Ext_Gea_Oil_Ket: DataTypes.TEXT,
    Main_Ext_Fil_Pre_Oil_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_TempM: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_ArusR: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_ArusS: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_ArusT: DataTypes.DECIMAL(5, 2),
    Main_Ext_Fil_Pre_Oil_Ket: DataTypes.TEXT,
    Metering_Ext_Gea_Oil_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_TempM: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_ArusR: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_ArusS: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_ArusT: DataTypes.DECIMAL(5, 2),
    Metering_Ext_Gea_Oil_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_4_grinder = db.define(
  "line_4_grinder",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Wst_Gnd_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_TempM: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_ArusR: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_ArusS: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_ArusT: DataTypes.DECIMAL(5, 2),
    Wst_Gnd_Ket: DataTypes.TEXT,
    Fed_Rol1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_TempM: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_ArusR: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_ArusS: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_ArusT: DataTypes.DECIMAL(5, 2),
    Fed_Rol1_Ket: DataTypes.TEXT,
    Tra_Grn_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Tra_Grn_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Tra_Grn_TempM: DataTypes.DECIMAL(5, 2),
    Tra_Grn_ArusR: DataTypes.DECIMAL(5, 2),
    Tra_Grn_ArusS: DataTypes.DECIMAL(5, 2),
    Tra_Grn_ArusT: DataTypes.DECIMAL(5, 2),
    Tra_Grn_Ket: DataTypes.TEXT,
    Mixer_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mixer_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mixer_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mixer_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mixer_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mixer_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mixer_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mixer_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mixer_TempM: DataTypes.DECIMAL(5, 2),
    Mixer_ArusR: DataTypes.DECIMAL(5, 2),
    Mixer_ArusS: DataTypes.DECIMAL(5, 2),
    Mixer_ArusT: DataTypes.DECIMAL(5, 2),
    Mixer_Ket: DataTypes.TEXT,
    Extruder_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Extruder_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Extruder_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Extruder_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Extruder_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Extruder_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Extruder_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Extruder_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Extruder_TempM: DataTypes.DECIMAL(5, 2),
    Extruder_ArusR: DataTypes.DECIMAL(5, 2),
    Extruder_ArusS: DataTypes.DECIMAL(5, 2),
    Extruder_ArusT: DataTypes.DECIMAL(5, 2),
    Extruder_Ket: DataTypes.TEXT,
    Wtr_Rmv_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_TempM: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusR: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusS: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusT: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_Ket: DataTypes.TEXT,
    Pellet_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pellet_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pellet_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pellet_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pellet_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pellet_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pellet_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pellet_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pellet_TempM: DataTypes.DECIMAL(5, 2),
    Pellet_ArusR: DataTypes.DECIMAL(5, 2),
    Pellet_ArusS: DataTypes.DECIMAL(5, 2),
    Pellet_ArusT: DataTypes.DECIMAL(5, 2),
    Pellet_Ket: DataTypes.TEXT,
    Blw_To_Sil_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_TempM: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_ArusR: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_ArusS: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_ArusT: DataTypes.DECIMAL(5, 2),
    Blw_To_Sil_Ket: DataTypes.TEXT,
    Oil_Pum_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Oil_Pum_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Oil_Pum_TempM: DataTypes.DECIMAL(5, 2),
    Oil_Pum_ArusR: DataTypes.DECIMAL(5, 2),
    Oil_Pum_ArusS: DataTypes.DECIMAL(5, 2),
    Oil_Pum_ArusT: DataTypes.DECIMAL(5, 2),
    Oil_Pum_Ket: DataTypes.TEXT,
    Hydralic_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Hydralic_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Hydralic_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Hydralic_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Hydralic_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Hydralic_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Hydralic_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Hydralic_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Hydralic_TempM: DataTypes.DECIMAL(5, 2),
    Hydralic_ArusR: DataTypes.DECIMAL(5, 2),
    Hydralic_ArusS: DataTypes.DECIMAL(5, 2),
    Hydralic_ArusT: DataTypes.DECIMAL(5, 2),
    Hydralic_Ket: DataTypes.TEXT,
    Wtr_Bth_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_TempM: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_ArusR: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_ArusS: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_ArusT: DataTypes.DECIMAL(5, 2),
    Wtr_Bth_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_4_mdo = db.define(
  "line_4_mdo",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Mdo1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo1_TempM: DataTypes.DECIMAL(5, 2),
    Mdo1_ArusR: DataTypes.DECIMAL(5, 2),
    Mdo1_ArusS: DataTypes.DECIMAL(5, 2),
    Mdo1_ArusT: DataTypes.DECIMAL(5, 2),
    Mdo1_Ket: DataTypes.TEXT,
    Mdo2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo2_TempM: DataTypes.DECIMAL(5, 2),
    Mdo2_ArusR: DataTypes.DECIMAL(5, 2),
    Mdo2_ArusS: DataTypes.DECIMAL(5, 2),
    Mdo2_ArusT: DataTypes.DECIMAL(5, 2),
    Mdo2_Ket: DataTypes.TEXT,
    Mdo3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo3_TempM: DataTypes.DECIMAL(5, 2),
    Mdo3_ArusR: DataTypes.DECIMAL(5, 2),
    Mdo3_ArusS: DataTypes.DECIMAL(5, 2),
    Mdo3_ArusT: DataTypes.DECIMAL(5, 2),
    Mdo3_Ket: DataTypes.TEXT,
    Fan_Mdo1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_Ket: DataTypes.TEXT,
    Fan_Mdo2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_Ket: DataTypes.TEXT,
    Fan_Mdo3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_Ket: DataTypes.TEXT,
    Preheating1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating1_TempM: DataTypes.DECIMAL(5, 2),
    Preheating1_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating1_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating1_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating1_Ket: DataTypes.TEXT,
    Preheating2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating2_TempM: DataTypes.DECIMAL(5, 2),
    Preheating2_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating2_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating2_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating2_Ket: DataTypes.TEXT,
    Preheating3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating3_TempM: DataTypes.DECIMAL(5, 2),
    Preheating3_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating3_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating3_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating3_Ket: DataTypes.TEXT,
    Preheating4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating4_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating4_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating4_TempM: DataTypes.DECIMAL(5, 2),
    Preheating4_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating4_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating4_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating4_Ket: DataTypes.TEXT,
    Preheating5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating5_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating5_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating5_TempM: DataTypes.DECIMAL(5, 2),
    Preheating5_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating5_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating5_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating5_Ket: DataTypes.TEXT,
    Drawing1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing1_TempM: DataTypes.DECIMAL(5, 2),
    Drawing1_ArusR: DataTypes.DECIMAL(5, 2),
    Drawing1_ArusS: DataTypes.DECIMAL(5, 2),
    Drawing1_ArusT: DataTypes.DECIMAL(5, 2),
    Drawing1_Ket: DataTypes.TEXT,
    Drawing2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing2_TempM: DataTypes.DECIMAL(5, 2),
    Drawing2_ArusR: DataTypes.DECIMAL(5, 2),
    Drawing2_ArusS: DataTypes.DECIMAL(5, 2),
    Drawing2_ArusT: DataTypes.DECIMAL(5, 2),
    Drawing2_Ket: DataTypes.TEXT,
    Drawing3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing3_TempM: DataTypes.DECIMAL(5, 2),
    Drawing3_ArusR: DataTypes.DECIMAL(5, 2),
    Drawing3_ArusS: DataTypes.DECIMAL(5, 2),
    Drawing3_ArusT: DataTypes.DECIMAL(5, 2),
    Drawing3_Ket: DataTypes.TEXT,
    Annealing1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing1_TempM: DataTypes.DECIMAL(5, 2),
    Annealing1_ArusR: DataTypes.DECIMAL(5, 2),
    Annealing1_ArusS: DataTypes.DECIMAL(5, 2),
    Annealing1_ArusT: DataTypes.DECIMAL(5, 2),
    Annealing1_Ket: DataTypes.TEXT,
    Annealing2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing2_TempM: DataTypes.DECIMAL(5, 2),
    Annealing2_ArusR: DataTypes.DECIMAL(5, 2),
    Annealing2_ArusS: DataTypes.DECIMAL(5, 2),
    Annealing2_ArusT: DataTypes.DECIMAL(5, 2),
    Annealing2_Ket: DataTypes.TEXT,
    Aux_Win_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Aux_Win_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Aux_Win_TempM: DataTypes.DECIMAL(5, 2),
    Aux_Win_ArusR: DataTypes.DECIMAL(5, 2),
    Aux_Win_ArusS: DataTypes.DECIMAL(5, 2),
    Aux_Win_ArusT: DataTypes.DECIMAL(5, 2),
    Aux_Win_Ket: DataTypes.TEXT,
    Crs_Cut_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_TempM: DataTypes.DECIMAL(5, 2),
    Crs_Cut_ArusR: DataTypes.DECIMAL(5, 2),
    Crs_Cut_ArusS: DataTypes.DECIMAL(5, 2),
    Crs_Cut_ArusT: DataTypes.DECIMAL(5, 2),
    Crs_Cut_Ket: DataTypes.TEXT,
    Str_Gap1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_TempM: DataTypes.DECIMAL(5, 2),
    Str_Gap1_ArusR: DataTypes.DECIMAL(5, 2),
    Str_Gap1_ArusS: DataTypes.DECIMAL(5, 2),
    Str_Gap1_ArusT: DataTypes.DECIMAL(5, 2),
    Str_Gap1_Ket: DataTypes.TEXT,
    Str_Gap2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_TempM: DataTypes.DECIMAL(5, 2),
    Str_Gap2_ArusR: DataTypes.DECIMAL(5, 2),
    Str_Gap2_ArusS: DataTypes.DECIMAL(5, 2),
    Str_Gap2_ArusT: DataTypes.DECIMAL(5, 2),
    Str_Gap2_Ket: DataTypes.TEXT,
    Str_Gap3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_TempM: DataTypes.DECIMAL(5, 2),
    Str_Gap3_ArusR: DataTypes.DECIMAL(5, 2),
    Str_Gap3_ArusS: DataTypes.DECIMAL(5, 2),
    Str_Gap3_ArusT: DataTypes.DECIMAL(5, 2),
    Str_Gap3_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_4_pullroll = db.define(
  "line_4_pullroll",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Pul_RoL1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_Ket: DataTypes.TEXT,
    Pul_RoL2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_Ket: DataTypes.TEXT,
    Col_Pum1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Pum1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Pum1_TempM: DataTypes.DECIMAL(5, 2),
    Col_Pum1_ArusR: DataTypes.DECIMAL(5, 2),
    Col_Pum1_ArusS: DataTypes.DECIMAL(5, 2),
    Col_Pum1_ArusT: DataTypes.DECIMAL(5, 2),
    Col_Pum1_Ket: DataTypes.TEXT,
    Col_Pum2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Pum2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Pum2_TempM: DataTypes.DECIMAL(5, 2),
    Col_Pum2_ArusR: DataTypes.DECIMAL(5, 2),
    Col_Pum2_ArusS: DataTypes.DECIMAL(5, 2),
    Col_Pum2_ArusT: DataTypes.DECIMAL(5, 2),
    Col_Pum2_Ket: DataTypes.TEXT,
    Col_Pum_Flame_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_TempM: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_ArusR: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_ArusS: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_ArusT: DataTypes.DECIMAL(5, 2),
    Col_Pum_Flame_Ket: DataTypes.TEXT,
    Rad_Pum_Flame_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_TempM: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_ArusR: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_ArusS: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_ArusT: DataTypes.DECIMAL(5, 2),
    Rad_Pum_Flame_Ket: DataTypes.TEXT,
    Fan_Corona_Exh1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_Ket: DataTypes.TEXT,
    Fan_Corona_Exh2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_Ket: DataTypes.TEXT,
    Fan_Flame_Ttn_Mix_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Flame_Ttn_Mix_Ket: DataTypes.TEXT,
    Cnt_Rol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_TempM: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_ArusR: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_ArusS: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_ArusT: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_Ket: DataTypes.TEXT,
    Fan_Con_Rol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Con_Rol_Ket: DataTypes.TEXT,
    Trn_rol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Trn_rol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Trn_rol_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Trn_rol_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Trn_rol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Trn_rol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Trn_rol_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Trn_rol_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Trn_rol_TempM: DataTypes.DECIMAL(5, 2),
    Trn_rol_ArusR: DataTypes.DECIMAL(5, 2),
    Trn_rol_ArusS: DataTypes.DECIMAL(5, 2),
    Trn_rol_ArusT: DataTypes.DECIMAL(5, 2),
    Trn_rol_Ket: DataTypes.TEXT,
    Win1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Win1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Win1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Win1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Win1_TempM: DataTypes.DECIMAL(5, 2),
    Win1_ArusR: DataTypes.DECIMAL(5, 2),
    Win1_ArusS: DataTypes.DECIMAL(5, 2),
    Win1_ArusT: DataTypes.DECIMAL(5, 2),
    Win1_Ket: DataTypes.TEXT,
    Win2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Win2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Win2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Win2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Win2_TempM: DataTypes.DECIMAL(5, 2),
    Win2_ArusR: DataTypes.DECIMAL(5, 2),
    Win2_ArusS: DataTypes.DECIMAL(5, 2),
    Win2_ArusT: DataTypes.DECIMAL(5, 2),
    Win2_Ket: DataTypes.TEXT,
    Hyd_Pum_Win_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_TempM: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_ArusR: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_ArusS: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_ArusT: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_4_silo = db.define(
  "line_4_silo",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Fan_Cvy_Grn_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_Ket: DataTypes.TEXT,
    Fed_Trc_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fed_Trc_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fed_Trc_TempM: DataTypes.DECIMAL(5, 2),
    Fed_Trc_ArusR: DataTypes.DECIMAL(5, 2),
    Fed_Trc_ArusS: DataTypes.DECIMAL(5, 2),
    Fed_Trc_ArusT: DataTypes.DECIMAL(5, 2),
    Fed_Trc_Ket: DataTypes.TEXT,
    Fan_Cvy_Coex1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_Ket: DataTypes.TEXT,
    Fan_Cvy_Coex2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_Ket: DataTypes.TEXT,
    Rot_Vlv_Dos_Main_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Rot_Vlv_Dos_Main_Ext_Ket: DataTypes.TEXT,
    Dos_Screw_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Dos_Screw_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Dos_Screw_TempM: DataTypes.DECIMAL(5, 2),
    Dos_Screw_ArusR: DataTypes.DECIMAL(5, 2),
    Dos_Screw_ArusS: DataTypes.DECIMAL(5, 2),
    Dos_Screw_ArusT: DataTypes.DECIMAL(5, 2),
    Dos_Screw_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_4_tdo = db.define(
  "line_4_tdo",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Tdo_Mtr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_TempM: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_ArusR: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_ArusS: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_ArusT: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_Ket: DataTypes.TEXT,
    Fan_Tdo_Mtr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_Ket: DataTypes.TEXT,
    Edge_Ds1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_TempM: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_ArusR: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_ArusS: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_ArusT: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_Ket: DataTypes.TEXT,
    Edge_Os2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_TempM: DataTypes.DECIMAL(5, 2),
    Edge_Os2_ArusR: DataTypes.DECIMAL(5, 2),
    Edge_Os2_ArusS: DataTypes.DECIMAL(5, 2),
    Edge_Os2_ArusT: DataTypes.DECIMAL(5, 2),
    Edge_Os2_Ket: DataTypes.TEXT,
    Chn_Ten_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_TempM: DataTypes.DECIMAL(5, 2),
    Chn_Ten_ArusR: DataTypes.DECIMAL(5, 2),
    Chn_Ten_ArusS: DataTypes.DECIMAL(5, 2),
    Chn_Ten_ArusT: DataTypes.DECIMAL(5, 2),
    Chn_Ten_Ket: DataTypes.TEXT,
    Lub_Inl_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_TempM: DataTypes.DECIMAL(5, 2),
    Lub_Inl_ArusR: DataTypes.DECIMAL(5, 2),
    Lub_Inl_ArusS: DataTypes.DECIMAL(5, 2),
    Lub_Inl_ArusT: DataTypes.DECIMAL(5, 2),
    Lub_Inl_Ket: DataTypes.TEXT,
    Lub_Out_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Out_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Out_TempM: DataTypes.DECIMAL(5, 2),
    Lub_Out_ArusR: DataTypes.DECIMAL(5, 2),
    Lub_Out_ArusS: DataTypes.DECIMAL(5, 2),
    Lub_Out_ArusT: DataTypes.DECIMAL(5, 2),
    Lub_Out_Ket: DataTypes.TEXT,
    Blt_Lub1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_TempM: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_ArusR: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_ArusS: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_ArusT: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_Ket: DataTypes.TEXT,
    Exh_Fan1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_TempM: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_ArusR: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_ArusS: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_ArusT: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_Ket: DataTypes.TEXT,
    Fan_Ds_Pre1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_Ket: DataTypes.TEXT,
    Fan_Ds_Pre2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_Ket: DataTypes.TEXT,
    Fan_Ds_Pre3_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_Ket: DataTypes.TEXT,
    Fan_Ds_Pre3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_Ket: DataTypes.TEXT,
    Fan_Ds_Dra1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_Ket: DataTypes.TEXT,
    Fan_Ds_Dra2_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_Ket: DataTypes.TEXT,
    Fan_Ds_Dra3_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_Ket: DataTypes.TEXT,
    Fan_Ds_Dra4_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_Ket: DataTypes.TEXT,
    Fan_Ds_Ann1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_Ket: DataTypes.TEXT,
    Fan_Ds_Ann2_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_Ket: DataTypes.TEXT,
    Fan_Ds_Ann3_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_Ket: DataTypes.TEXT,
    Fan_Ds_Col_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_Ket: DataTypes.TEXT,
    Fan_Os_Pre1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_Ket: DataTypes.TEXT,
    Fan_Os_Pre2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_Ket: DataTypes.TEXT,
    Fan_Os_Pre3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra4_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_Ket: DataTypes.TEXT,
    Fan_Os_Ann1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_Ket: DataTypes.TEXT,
    Fan_Os_Ann2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_Ket: DataTypes.TEXT,
    Fan_Os_Ann3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_Ket: DataTypes.TEXT,
    Fan_Neu_Os_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_Ket: DataTypes.TEXT,
    Exh_Fan2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_TempM: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_ArusR: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_ArusS: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_ArusT: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_Ket: DataTypes.TEXT,
    Blt_Lub2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_TempM: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_ArusR: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_ArusS: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_ArusT: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);

module.exports = {
  //getAlluser,
  line_4_casting,
  line_4_ext,
  line_4_grinder,
  line_4_mdo,
  line_4_pullroll,
  line_4_silo,
}(async () => {
  await db.sync();
})();
