const { Sequelize, DataTypes } = require("sequelize");
const db = require("../config/Dbconnect.js");

const line_5_casting = db.define(
  "line_5_casting",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Chr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_TempM: DataTypes.DECIMAL(5, 2),
    Chr_ArusR: DataTypes.DECIMAL(5, 2),
    Chr_ArusS: DataTypes.DECIMAL(5, 2),
    Chr_ArusT: DataTypes.DECIMAL(5, 2),
    Chr_Ket: DataTypes.TEXT,
    Fan_Chr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Chr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Chr_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Chr_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Chr_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Chr_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Chr_Ket: DataTypes.TEXT,
    Chr_Pum_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Pum_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Pum_TempM: DataTypes.DECIMAL(5, 2),
    Chr_Pum_ArusR: DataTypes.DECIMAL(5, 2),
    Chr_Pum_ArusS: DataTypes.DECIMAL(5, 2),
    Chr_Pum_ArusT: DataTypes.DECIMAL(5, 2),
    Chr_Pum_Ket: DataTypes.TEXT,
    Col_Die_Blt_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_TempM: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_ArusR: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_ArusS: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_ArusT: DataTypes.DECIMAL(5, 2),
    Col_Die_Blt_Ket: DataTypes.TEXT,
    Air_Knf_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Air_Knf_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Air_Knf_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Air_Knf_TempM: DataTypes.DECIMAL(5, 2),
    Air_Knf_ArusR: DataTypes.DECIMAL(5, 2),
    Air_Knf_ArusS: DataTypes.DECIMAL(5, 2),
    Air_Knf_ArusT: DataTypes.DECIMAL(5, 2),
    Air_Knf_Ket: DataTypes.TEXT,
    Wtr_Rmv_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_TempM: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusR: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusS: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_ArusT: DataTypes.DECIMAL(5, 2),
    Wtr_Rmv_Ket: DataTypes.TEXT,
    Chr_Wtr_Bth_Pum_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_TempM: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_ArusR: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_ArusS: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_ArusT: DataTypes.DECIMAL(5, 2),
    Chr_Wtr_Bth_Pum_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_5_erema = db.define(
  "line_5_erema",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Motor_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Motor_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Motor_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Motor_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Motor_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Motor_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Motor_Ext_Ket: DataTypes.TEXT,
    Motor_Compactor_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_TempM: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_ArusR: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_ArusS: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_ArusT: DataTypes.DECIMAL(5, 2),
    Motor_Compactor_Ket: DataTypes.TEXT,
    Vib_Mot1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_TempM: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_ArusR: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_ArusS: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_ArusT: DataTypes.DECIMAL(5, 2),
    Vib_Mot1_Ket: DataTypes.TEXT,
    Vib_Mot2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_TempM: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_ArusR: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_ArusS: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_ArusT: DataTypes.DECIMAL(5, 2),
    Vib_Mot2_Ket: DataTypes.TEXT,
    Centri_Dry_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Centri_Dry_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Centri_Dry_TempM: DataTypes.DECIMAL(5, 2),
    Centri_Dry_ArusR: DataTypes.DECIMAL(5, 2),
    Centri_Dry_ArusS: DataTypes.DECIMAL(5, 2),
    Centri_Dry_ArusT: DataTypes.DECIMAL(5, 2),
    Centri_Dry_Ket: DataTypes.TEXT,
    Cvy_Fed_Mat_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_TempM: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_ArusR: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_ArusS: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_ArusT: DataTypes.DECIMAL(5, 2),
    Cvy_Fed_Mat_Ket: DataTypes.TEXT,
    Fan_Col_Blw1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw1_Ket: DataTypes.TEXT,
    Fan_Col_Blw2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Col_Blw2_Ket: DataTypes.TEXT,
    Pelletizer_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pelletizer_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pelletizer_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pelletizer_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pelletizer_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pelletizer_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pelletizer_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pelletizer_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pelletizer_TempM: DataTypes.DECIMAL(5, 2),
    Pelletizer_ArusR: DataTypes.DECIMAL(5, 2),
    Pelletizer_ArusS: DataTypes.DECIMAL(5, 2),
    Pelletizer_ArusT: DataTypes.DECIMAL(5, 2),
    Pelletizer_Ket: DataTypes.TEXT,
    Wtr_Bath_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_TempM: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_ArusR: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_ArusS: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_ArusT: DataTypes.DECIMAL(5, 2),
    Wtr_Bath_Ket: DataTypes.TEXT,
    Blw_Mat_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Blw_Mat_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Blw_Mat_TempM: DataTypes.DECIMAL(5, 2),
    Blw_Mat_ArusR: DataTypes.DECIMAL(5, 2),
    Blw_Mat_ArusS: DataTypes.DECIMAL(5, 2),
    Blw_Mat_ArusT: DataTypes.DECIMAL(5, 2),
    Blw_Mat_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_5_ext = db.define(
  "line_5_ext",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Main_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Main_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Main_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Main_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Main_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Main_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Main_Ext_Ket: DataTypes.TEXT,
    Fan_Main_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Main_Ext_Ket: DataTypes.TEXT,
    Cascade_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Cascade_Ext_Ket: DataTypes.TEXT,
    Fan_Cascade_Ext_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cascade_Ext_Ket: DataTypes.TEXT,
    Co_Ext1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext1_TempM: DataTypes.DECIMAL(5, 2),
    Co_Ext1_ArusR: DataTypes.DECIMAL(5, 2),
    Co_Ext1_ArusS: DataTypes.DECIMAL(5, 2),
    Co_Ext1_ArusT: DataTypes.DECIMAL(5, 2),
    Co_Ext1_Ket: DataTypes.TEXT,
    Co_Ext2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Co_Ext2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Co_Ext2_TempM: DataTypes.DECIMAL(5, 2),
    Co_Ext2_ArusR: DataTypes.DECIMAL(5, 2),
    Co_Ext2_ArusS: DataTypes.DECIMAL(5, 2),
    Co_Ext2_ArusT: DataTypes.DECIMAL(5, 2),
    Co_Ext2_Ket: DataTypes.TEXT,
    Fan_Co_Ext1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext1_Ket: DataTypes.TEXT,
    Fan_Co_Ext2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Co_Ext2_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_5_mdo = db.define(
  "line_5_mdo",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Mdo1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo1_TempM: DataTypes.DECIMAL(5, 2),
    Mdo1_ArusR: DataTypes.DECIMAL(5, 2),
    Mdo1_ArusS: DataTypes.DECIMAL(5, 2),
    Mdo1_ArusT: DataTypes.DECIMAL(5, 2),
    Mdo1_Ket: DataTypes.TEXT,
    Mdo2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo2_TempM: DataTypes.DECIMAL(5, 2),
    Mdo2_ArusR: DataTypes.DECIMAL(5, 2),
    Mdo2_ArusS: DataTypes.DECIMAL(5, 2),
    Mdo2_ArusT: DataTypes.DECIMAL(5, 2),
    Mdo2_Ket: DataTypes.TEXT,
    Mdo3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Mdo3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Mdo3_TempM: DataTypes.DECIMAL(5, 2),
    Mdo3_ArusR: DataTypes.DECIMAL(5, 2),
    Mdo3_ArusS: DataTypes.DECIMAL(5, 2),
    Mdo3_ArusT: DataTypes.DECIMAL(5, 2),
    Mdo3_Ket: DataTypes.TEXT,
    Fan_Mdo1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Mdo1_Ket: DataTypes.TEXT,
    Fan_Mdo2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Mdo2_Ket: DataTypes.TEXT,
    Fan_Mdo3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Mdo3_Ket: DataTypes.TEXT,
    Preheating1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating1_TempM: DataTypes.DECIMAL(5, 2),
    Preheating1_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating1_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating1_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating1_Ket: DataTypes.TEXT,
    Preheating2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating2_TempM: DataTypes.DECIMAL(5, 2),
    Preheating2_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating2_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating2_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating2_Ket: DataTypes.TEXT,
    Preheating3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating3_TempM: DataTypes.DECIMAL(5, 2),
    Preheating3_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating3_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating3_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating3_Ket: DataTypes.TEXT,
    Preheating4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating4_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating4_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating4_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating4_TempM: DataTypes.DECIMAL(5, 2),
    Preheating4_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating4_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating4_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating4_Ket: DataTypes.TEXT,
    Preheating5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating5_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating5_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Preheating5_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Preheating5_TempM: DataTypes.DECIMAL(5, 2),
    Preheating5_ArusR: DataTypes.DECIMAL(5, 2),
    Preheating5_ArusS: DataTypes.DECIMAL(5, 2),
    Preheating5_ArusT: DataTypes.DECIMAL(5, 2),
    Preheating5_Ket: DataTypes.TEXT,
    Drawing1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing1_TempM: DataTypes.DECIMAL(5, 2),
    Drawing1_ArusR: DataTypes.DECIMAL(5, 2),
    Drawing1_ArusS: DataTypes.DECIMAL(5, 2),
    Drawing1_ArusT: DataTypes.DECIMAL(5, 2),
    Drawing1_Ket: DataTypes.TEXT,
    Drawing2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing2_TempM: DataTypes.DECIMAL(5, 2),
    Drawing2_ArusR: DataTypes.DECIMAL(5, 2),
    Drawing2_ArusS: DataTypes.DECIMAL(5, 2),
    Drawing2_ArusT: DataTypes.DECIMAL(5, 2),
    Drawing2_Ket: DataTypes.TEXT,
    Drawing3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Drawing3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Drawing3_TempM: DataTypes.DECIMAL(5, 2),
    Drawing3_ArusR: DataTypes.DECIMAL(5, 2),
    Drawing3_ArusS: DataTypes.DECIMAL(5, 2),
    Drawing3_ArusT: DataTypes.DECIMAL(5, 2),
    Drawing3_Ket: DataTypes.TEXT,
    Annealing1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing1_TempM: DataTypes.DECIMAL(5, 2),
    Annealing1_ArusR: DataTypes.DECIMAL(5, 2),
    Annealing1_ArusS: DataTypes.DECIMAL(5, 2),
    Annealing1_ArusT: DataTypes.DECIMAL(5, 2),
    Annealing1_Ket: DataTypes.TEXT,
    Annealing2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Annealing2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Annealing2_TempM: DataTypes.DECIMAL(5, 2),
    Annealing2_ArusR: DataTypes.DECIMAL(5, 2),
    Annealing2_ArusS: DataTypes.DECIMAL(5, 2),
    Annealing2_ArusT: DataTypes.DECIMAL(5, 2),
    Annealing2_Ket: DataTypes.TEXT,
    Aux_Win_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Aux_Win_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Aux_Win_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Aux_Win_TempM: DataTypes.DECIMAL(5, 2),
    Aux_Win_ArusR: DataTypes.DECIMAL(5, 2),
    Aux_Win_ArusS: DataTypes.DECIMAL(5, 2),
    Aux_Win_ArusT: DataTypes.DECIMAL(5, 2),
    Aux_Win_Ket: DataTypes.TEXT,
    Crs_Cut_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Crs_Cut_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Crs_Cut_TempM: DataTypes.DECIMAL(5, 2),
    Crs_Cut_ArusR: DataTypes.DECIMAL(5, 2),
    Crs_Cut_ArusS: DataTypes.DECIMAL(5, 2),
    Crs_Cut_ArusT: DataTypes.DECIMAL(5, 2),
    Crs_Cut_Ket: DataTypes.TEXT,
    Str_Gap1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap1_TempM: DataTypes.DECIMAL(5, 2),
    Str_Gap1_ArusR: DataTypes.DECIMAL(5, 2),
    Str_Gap1_ArusS: DataTypes.DECIMAL(5, 2),
    Str_Gap1_ArusT: DataTypes.DECIMAL(5, 2),
    Str_Gap1_Ket: DataTypes.TEXT,
    Str_Gap2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap2_TempM: DataTypes.DECIMAL(5, 2),
    Str_Gap2_ArusR: DataTypes.DECIMAL(5, 2),
    Str_Gap2_ArusS: DataTypes.DECIMAL(5, 2),
    Str_Gap2_ArusT: DataTypes.DECIMAL(5, 2),
    Str_Gap2_Ket: DataTypes.TEXT,
    Str_Gap3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Str_Gap3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Str_Gap3_TempM: DataTypes.DECIMAL(5, 2),
    Str_Gap3_ArusR: DataTypes.DECIMAL(5, 2),
    Str_Gap3_ArusS: DataTypes.DECIMAL(5, 2),
    Str_Gap3_ArusT: DataTypes.DECIMAL(5, 2),
    Str_Gap3_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_5_pullroll = db.define(
  "line_5_pullroll",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Pul_RoL1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL1_Ket: DataTypes.TEXT,
    Pul_RoL2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL2_Ket: DataTypes.TEXT,
    Pul_RoL3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL3_Ket: DataTypes.TEXT,
    Pul_RoL4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL4_Ket: DataTypes.TEXT,
    Pul_RoL5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_TempM: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_ArusR: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_ArusS: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_ArusT: DataTypes.DECIMAL(5, 2),
    Pul_RoL5_Ket: DataTypes.TEXT,
    Fan_Pul_Rol3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol3_Ket: DataTypes.TEXT,
    Fan_Pul_Rol4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol4_Ket: DataTypes.TEXT,
    Fan_Pul_Rol5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Pul_Rol5_Ket: DataTypes.TEXT,
    Pump_HCU1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_TempM: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_ArusR: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_ArusS: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_ArusT: DataTypes.DECIMAL(5, 2),
    Pump_HCU1_Ket: DataTypes.TEXT,
    Pump_HCU2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_TempM: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_ArusR: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_ArusS: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_ArusT: DataTypes.DECIMAL(5, 2),
    Pump_HCU2_Ket: DataTypes.TEXT,
    Pump_HCU3_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_TempM: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_ArusR: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_ArusS: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_ArusT: DataTypes.DECIMAL(5, 2),
    Pump_HCU3_Ket: DataTypes.TEXT,
    Pump_HCU4_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_TempM: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_ArusR: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_ArusS: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_ArusT: DataTypes.DECIMAL(5, 2),
    Pump_HCU4_Ket: DataTypes.TEXT,
    Pump_HCU5_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_TempM: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_ArusR: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_ArusS: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_ArusT: DataTypes.DECIMAL(5, 2),
    Pump_HCU5_Ket: DataTypes.TEXT,
    Fan_Corona_Exh1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh1_Ket: DataTypes.TEXT,
    Fan_Corona_Exh2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Corona_Exh2_Ket: DataTypes.TEXT,
    Exh_Edge_Trm_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_TempM: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_ArusR: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_ArusS: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_ArusT: DataTypes.DECIMAL(5, 2),
    Exh_Edge_Trm_Ket: DataTypes.TEXT,
    Trf_Flf_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Trf_Flf_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Trf_Flf_TempM: DataTypes.DECIMAL(5, 2),
    Trf_Flf_ArusR: DataTypes.DECIMAL(5, 2),
    Trf_Flf_ArusS: DataTypes.DECIMAL(5, 2),
    Trf_Flf_ArusT: DataTypes.DECIMAL(5, 2),
    Trf_Flf_Ket: DataTypes.TEXT,
    Small_Grndr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Small_Grndr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Small_Grndr_TempM: DataTypes.DECIMAL(5, 2),
    Small_Grndr_ArusR: DataTypes.DECIMAL(5, 2),
    Small_Grndr_ArusS: DataTypes.DECIMAL(5, 2),
    Small_Grndr_ArusT: DataTypes.DECIMAL(5, 2),
    Small_Grndr_Ket: DataTypes.TEXT,
    Col_Brnr_Flame_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_TempM: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_ArusR: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_ArusS: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_ArusT: DataTypes.DECIMAL(5, 2),
    Col_Brnr_Flame_Ket: DataTypes.TEXT,
    Combution_Flame_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Combution_Flame_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Combution_Flame_TempM: DataTypes.DECIMAL(5, 2),
    Combution_Flame_ArusR: DataTypes.DECIMAL(5, 2),
    Combution_Flame_ArusS: DataTypes.DECIMAL(5, 2),
    Combution_Flame_ArusT: DataTypes.DECIMAL(5, 2),
    Combution_Flame_Ket: DataTypes.TEXT,
    Cnt_Rol_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_TempM: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_ArusR: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_ArusS: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_ArusT: DataTypes.DECIMAL(5, 2),
    Cnt_Rol_Ket: DataTypes.TEXT,
    Win1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Win1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Win1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Win1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Win1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Win1_TempM: DataTypes.DECIMAL(5, 2),
    Win1_ArusR: DataTypes.DECIMAL(5, 2),
    Win1_ArusS: DataTypes.DECIMAL(5, 2),
    Win1_ArusT: DataTypes.DECIMAL(5, 2),
    Win1_Ket: DataTypes.TEXT,
    Win2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Win2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Win2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Win2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Win2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Win2_TempM: DataTypes.DECIMAL(5, 2),
    Win2_ArusR: DataTypes.DECIMAL(5, 2),
    Win2_ArusS: DataTypes.DECIMAL(5, 2),
    Win2_ArusT: DataTypes.DECIMAL(5, 2),
    Win2_Ket: DataTypes.TEXT,
    Fan_Win1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Win1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Win1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Win1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Win1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Win1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Win1_Ket: DataTypes.TEXT,
    Fan_Win2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Win2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Win2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Win2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Win2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Win2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Win2_Ket: DataTypes.TEXT,
    Thck_Gauge_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_TempM: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_ArusR: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_ArusS: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_ArusT: DataTypes.DECIMAL(5, 2),
    Thck_Gauge_Ket: DataTypes.TEXT,
    Hyd_Pum_Win_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_TempM: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_ArusR: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_ArusS: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_ArusT: DataTypes.DECIMAL(5, 2),
    Hyd_Pum_Win_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_5_silo = db.define(
  "line_5_silo",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Fan_Cvy_Grn_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Grn_Ket: DataTypes.TEXT,
    Suc_Con_Fan_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_TempM: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_ArusR: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_ArusS: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_ArusT: DataTypes.DECIMAL(5, 2),
    Suc_Con_Fan_Ket: DataTypes.TEXT,
    Fan_Cvy_Coex1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex1_Ket: DataTypes.TEXT,
    Fan_Cvy_Coex2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Cvy_Coex2_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);
const line_5_tdo = db.define(
  "line_5_tdo",
  {
    Tanggal: {
      type: Sequelize.DATE,
      primaryKey: true,
    },
    Nama: DataTypes.STRING(30),
    Status: DataTypes.TINYINT(1),
    Tanggal_Status: DataTypes.DATE,
    Tdo_Mtr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_TempM: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_ArusR: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_ArusS: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_ArusT: DataTypes.DECIMAL(5, 2),
    Tdo_Mtr_Ket: DataTypes.TEXT,
    Fan_Tdo_Mtr_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Tdo_Mtr_Ket: DataTypes.TEXT,
    Edge_Ds1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_TempM: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_ArusR: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_ArusS: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_ArusT: DataTypes.DECIMAL(5, 2),
    Edge_Ds1_Ket: DataTypes.TEXT,
    Edge_Os2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Edge_Os2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Edge_Os2_TempM: DataTypes.DECIMAL(5, 2),
    Edge_Os2_ArusR: DataTypes.DECIMAL(5, 2),
    Edge_Os2_ArusS: DataTypes.DECIMAL(5, 2),
    Edge_Os2_ArusT: DataTypes.DECIMAL(5, 2),
    Edge_Os2_Ket: DataTypes.TEXT,
    Chn_Ten_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Chn_Ten_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Chn_Ten_TempM: DataTypes.DECIMAL(5, 2),
    Chn_Ten_ArusR: DataTypes.DECIMAL(5, 2),
    Chn_Ten_ArusS: DataTypes.DECIMAL(5, 2),
    Chn_Ten_ArusT: DataTypes.DECIMAL(5, 2),
    Chn_Ten_Ket: DataTypes.TEXT,
    Lub_Inl_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Inl_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Inl_TempM: DataTypes.DECIMAL(5, 2),
    Lub_Inl_ArusR: DataTypes.DECIMAL(5, 2),
    Lub_Inl_ArusS: DataTypes.DECIMAL(5, 2),
    Lub_Inl_ArusT: DataTypes.DECIMAL(5, 2),
    Lub_Inl_Ket: DataTypes.TEXT,
    Lub_Out_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Out_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Lub_Out_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Lub_Out_TempM: DataTypes.DECIMAL(5, 2),
    Lub_Out_ArusR: DataTypes.DECIMAL(5, 2),
    Lub_Out_ArusS: DataTypes.DECIMAL(5, 2),
    Lub_Out_ArusT: DataTypes.DECIMAL(5, 2),
    Lub_Out_Ket: DataTypes.TEXT,
    Blt_Lub1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_TempM: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_ArusR: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_ArusS: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_ArusT: DataTypes.DECIMAL(5, 2),
    Blt_Lub1_Ket: DataTypes.TEXT,
    Exh_Fan1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_TempM: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_ArusR: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_ArusS: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_ArusT: DataTypes.DECIMAL(5, 2),
    Exh_Fan1_Ket: DataTypes.TEXT,
    Fan_Ds_Pre1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre1_1_Ket: DataTypes.TEXT,
    Fan_Ds_Pre2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre2_2_Ket: DataTypes.TEXT,
    Fan_Ds_Pre3_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_1_Ket: DataTypes.TEXT,
    Fan_Ds_Pre3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Pre3_2_Ket: DataTypes.TEXT,
    Fan_Ds_Dra1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra1_1_Ket: DataTypes.TEXT,
    Fan_Ds_Dra2_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra2_1_Ket: DataTypes.TEXT,
    Fan_Ds_Dra3_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra3_1_Ket: DataTypes.TEXT,
    Fan_Ds_Dra4_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Dra4_1_Ket: DataTypes.TEXT,
    Fan_Ds_Ann1_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann1_1_Ket: DataTypes.TEXT,
    Fan_Ds_Ann2_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann2_1_Ket: DataTypes.TEXT,
    Fan_Ds_Ann3_1_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Ann3_1_Ket: DataTypes.TEXT,
    Fan_Ds_Col_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Ds_Col_Ket: DataTypes.TEXT,
    Fan_Os_Pre1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre1_2_Ket: DataTypes.TEXT,
    Fan_Os_Pre2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre2_2_Ket: DataTypes.TEXT,
    Fan_Os_Pre3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Pre3_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra1_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra2_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra3_2_Ket: DataTypes.TEXT,
    Fan_Os_Dra4_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Dra4_2_Ket: DataTypes.TEXT,
    Fan_Os_Ann1_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann1_2_Ket: DataTypes.TEXT,
    Fan_Os_Ann2_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann2_2_Ket: DataTypes.TEXT,
    Fan_Os_Ann3_2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Os_Ann3_2_Ket: DataTypes.TEXT,
    Fan_Neu_Os_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_TempM: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_ArusR: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_ArusS: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_ArusT: DataTypes.DECIMAL(5, 2),
    Fan_Neu_Os_Ket: DataTypes.TEXT,
    Exh_Fan2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_TempM: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_ArusR: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_ArusS: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_ArusT: DataTypes.DECIMAL(5, 2),
    Exh_Fan2_Ket: DataTypes.TEXT,
    Blt_Lub2_VDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Vms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Vge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Hms: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_VNDE_Hge: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_TempM: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_ArusR: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_ArusS: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_ArusT: DataTypes.DECIMAL(5, 2),
    Blt_Lub2_Ket: DataTypes.TEXT,
  },
  {
    freezeTableName: true,
    timestamps: false,
  }
);

module.exports = {
  //getAlluser,
  line_5_casting,
  line_5_erema,
  line_5_ext,
  line_5_mdo,
  line_5_pullroll,
  line_5_silo,
  line_5_tdo,
}(async () => {
  await db.sync();
})();
